const productsData = [
    {
        "id": "1",
        "code": "DSC00764",
        "name_en": "Salty Halawa",
        "name_ar": "حلاوة طحينية مالحة",
        "desc_en": "Halawa mixed with cheese and oil.",
        "desc_ar": "حلاوة طحينية ممزوجة بالجبنة والزيت.",
        "image": "/src/assets/Menu/DSC00764/DSC00764.JPG",
        "category_en": "breakfast, appetizers",
        "category_ar": "فطار, مقبلات",
        "calories": 136,
        "price": 15,
        "rating": 5,
        "available": true,
        "trendy": false,
        "prepTime": 5,
        "cookTime_en": 0,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": ["halawa", "white cheese", "olive oil"],
        "ingredients_ar": ["حلاوة طحينية", "جبنة بيضاء", "زيت زيتون"],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "A unique mix of sweetness and saltiness.",
        "notes_ar": "مزيج فريد من الحلاوة والملوحة."
    },
    {
        "id": "2",
        "code": "DSC00840",
        "name_en": "Olives",
        "name_ar": "زيتون",
        "desc_en": "A selection of green and black olives pickled in To'mah jars.",
        "desc_ar": "تشكيلة من الزيتون الأخضر والأسود والمخلل في برطمانات طعمة.",
        "image": "/src/assets/Menu/DSC00840/DSC00840.JPG",
        "category_en": "appetizers",
        "category_ar": "مقبلات",
        "calories": 141,
        "price": 9,
        "rating": 4,
        "available": true,
        "trendy": false,
        "prepTime": 0,
        "cookTime_en": 0,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": ["green olives", "black olives", "water", "salt", "preservatives"],
        "ingredients_ar": ["زيتون أخضر", "زيتون أسود", "ماء", "ملح", "مواد حافظة"],
        "isVegetarian": true,
        "isVegan": true,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Pickled in To'mah jars.",
        "notes_ar": "مخلل في برطمانات طعمة."
    },
    {
        "id": "3",
        "code": "DSC00865",
        "name_en": "Labneh with Beetroot",
        "name_ar": "لبنة بالبنجر",
        "desc_en": "Labneh with a very special beetroot mix.",
        "desc_ar": "لبنة بخلطة مميزة جدا من البنجر.",
        "image": "/src/assets/Menu/DSC00865/DSC00865.JPG",
        "category_en": "appetizers",
        "category_ar": "مقبلات",
        "calories": 249,
        "price": 13,
        "rating": 3,
        "available": true,
        "trendy": true,
        "prepTime": 10,
        "cookTime_en": 0,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": ["labneh", "beetroot", "garlic", "mint", "olive oil", "salt"],
        "ingredients_ar": ["لبنة", "بنجر", "ثوم", "نعناع", "زيت زيتون", "ملح"],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Labneh with a refreshing and unique flavor.",
        "notes_ar": "لبنة بنكهة منعشة ومميزة."
    },
    {
        "id": "4",
        "code": "DSC00875",
        "name_en": "Honey and Clotted Cream",
        "name_ar": "عسل وقشطة",
        "desc_en": "Qeshta and honey mix with pistachio.",
        "desc_ar": "خلطة العسل والقشطة ورشة الفستق.",
        "image": "/src/assets/Menu/DSC00875/DSC00875.JPG",
        "category_en": "breakfast, desserts",
        "category_ar": "فطار, حلويات",
        "calories": 328,
        "price": 17,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 5,
        "cookTime_en": 0,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": ["clotted cream (qeshta)", "honey", "pistachios"],
        "ingredients_ar": ["قشطة بلدي", "عسل", "فستق حلبي"],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Served as a breakfast dish or light dessert.",
        "notes_ar": "تقدم كوجبة فطار أو حلوى خفيفة."
    },
    {
        "id": "5",
        "code": "DSC00965",
        "name_en": "Labneh",
        "name_ar": "لبنة سادة",
        "desc_en": "Plain Labneh for our loved ones.",
        "desc_ar": "لبنة سادة للحبايب.",
        "image": "/src/assets/Menu/DSC00965/DSC00965.JPG",
        "category_en": "appetizers",
        "category_ar": "مقبلات",
        "calories": 332,
        "price": 15,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 5,
        "cookTime_en": 0,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": ["labneh", "olive oil", "mint", "salt"],
        "ingredients_ar": ["لبنة", "زيت زيتون", "نعناع", "ملح"],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Served as an appetizer or part of breakfast.",
        "notes_ar": "تقدم كفاتح للشهية أو جزء من وجبة الإفطار."
    },
    {
        "id": "6",
        "code": "DSC00973",
        "name_en": "Yellow Cheese with Eggplant",
        "name_ar": "جبنة صفراء بالباذنجان",
        "desc_en": "A blend of cheddar cheese and fried eggplant with an irresistible sauce.",
        "desc_ar": "خليط الجبنة التشيدر والباذنجان المقلي بصوص لا يقاوم.",
        "image": "/src/assets/Menu/DSC00973/DSC00973.JPG",
        "category_en": "appetizers",
        "category_ar": "مقبلات",
        "calories": 110,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 15,
        "cookTime_en": 10,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "cheddar cheese",
            "eggplant",
            "frying oil",
            "parsley",
            "mint",
            "garlic",
            "olive oil",
            "red pepper",
            "salt"
        ],
        "ingredients_ar": [
            "جبنة تشيدر",
            "باذنجان",
            "زيت للقلي",
            "بقدونس",
            "نعناع",
            "ثوم",
            "زيت زيتون",
            "فلفل أحمر",
            "ملح"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Served as a side dish or appetizer.",
        "notes_ar": "يقدم كطبق جانبي أو مقبلات."
    },
    {
        "id": "7",
        "code": "DSC00993",
        "name_en": "To'mah Shakshuka",
        "name_ar": "شكشوكة طعمة",
        "desc_en": "The authentic Hejazi Shakshuka.",
        "desc_ar": "الشكشوكة الحجازية الأصيلة.",
        "image": "/src/assets/Menu/DSC00993/DSC00993.JPG",
        "category_en": "breakfast",
        "category_ar": "فطار",
        "calories": null,
        "price": 17,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": 10,
        "cookTime_en": 20,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "eggs",
            "tomatoes",
            "peppers",
            "onions",
            "garlic",
            "Hejazi spices",
            "oil"
        ],
        "ingredients_ar": [
            "بيض",
            "طماطم",
            "فلفل",
            "بصل",
            "ثوم",
            "بهارات حجازية",
            "زيت"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Authentic and delicious Hejazi shakshuka.",
        "notes_ar": "شكشوكة حجازية أصيلة ولذيذة."
    },
    {
        "id": "8",
        "code": "DSC01010",
        "name_en": "To'mah Eggs",
        "name_ar": "بيض طعمة",
        "desc_en": "Eggs with vegetables and melted cheese, prepared in the chef's special way.",
        "desc_ar": "بيض بالخضار والجبنة المطبوخة بطريقة الشيف الخاصة.",
        "image": "/src/assets/Menu/DSC01010/DSC01010.JPG",
        "category_en": "breakfast",
        "category_ar": "فطار",
        "calories": null,
        "price": 23,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": 10,
        "cookTime_en": 15,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "eggs",
            "tomatoes",
            "onions",
            "peppers",
            "cheese",
            "cream/qeshta",
            "spices"
        ],
        "ingredients_ar": [
            "بيض",
            "طماطم",
            "بصل",
            "فلفل",
            "جبنة",
            "قشطة/كريمة",
            "بهارات"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Special egg dish prepared in the chef's way.",
        "notes_ar": "طبق بيض مميز بطريقة الشيف."
    },
    {
        "id": "9",
        "code": "DSC01012",
        "name_en": "Butter Eggs",
        "name_ar": "بيض بالزبدة",
        "desc_en": "Egg fried with butter, salt, and Madinah's special Dukkah spice mix.",
        "desc_ar": "حلقات البيض مشوحة بالزبدة والملح ودقة المدينة المميزة.",
        "image": "/src/assets/Menu/DSC01012/DSC01012.JPG",
        "category_en": "breakfast",
        "category_ar": "فطار",
        "calories": null,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 5,
        "cookTime_en": 10,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "eggs",
            "butter",
            "salt",
            "Madinah's Dukkah spice mix"
        ],
        "ingredients_ar": [
            "بيض",
            "زبدة",
            "ملح",
            "دقة المدينة"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Quick and delicious breakfast dish.",
        "notes_ar": "طبق فطار سريع ولذيذ."
    },
    {
        "id": "10",
        "code": "DSC01024",
        "name_en": "Fried Eggs",
        "name_ar": "بيض مقلي",
        "desc_en": "For the good ones.",
        "desc_ar": "بيض الطيبين.",
        "image": "/src/assets/Menu/DSC01024/DSC01024.JPG",
        "category_en": "breakfast",
        "category_ar": "فطار",
        "calories": null,
        "price": 17,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 2,
        "cookTime_en": 5,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "eggs",
            "oil/butter",
            "salt",
            "pepper",
            "parsley/coriander (for garnish)"
        ],
        "ingredients_ar": [
            "بيض",
            "زيت/زبدة",
            "ملح",
            "فلفل",
            "بقدونس/كزبرة (للتزيين)"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Simple and delicious breakfast dish.",
        "notes_ar": "طبق فطار بسيط ولذيذ."
    },
    {
        "id": "11",
        "code": "DSC01141",
        "name_en": "Hawah Fattah",
        "name_ar": "فتة هوا",
        "desc_en": "Fattah with whole-grain bread in chicken broth.",
        "desc_ar": "فتة عيش حب بمرقة الدجاج.",
        "image": "/src/assets/Menu/DSC01141/DSC01141.JPG",
        "category_en": "breakfast, main dishes",
        "category_ar": "فطار, أطباق رئيسية",
        "calories": null,
        "price": 30,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": 15,
        "cookTime_en": 25,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "whole-grain bread",
            "chicken broth",
            "yogurt/tahini",
            "parsley",
            "pine nuts/almonds",
            "garlic (likely)",
            "ghee (likely)"
        ],
        "ingredients_ar": [
            "خبز أسمر/حبوب كاملة",
            "مرقة دجاج",
            "زبادي/طحينة",
            "بقدونس",
            "صنوبر/لوز",
            "ثوم (محتمل)",
            "سمن (محتمل)"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Delicious fattah dish with chicken broth.",
        "notes_ar": "طبق فتة شهي بمرقة الدجاج."
    },
    {
        "id": "12",
        "code": "DSC01144",
        "name_en": "Cook's Market Liver",
        "name_ar": "كبدة سوق الطباخة",
        "desc_en": "Liver fried with vegetables over high heat, served with whole-grain bread, lemon wedges, and tahini.",
        "desc_ar": "كبدة مشوحة بالخضار على نار عالية وتقدم بخبز أسمر وقطع الليمون والطحينة.",
        "image": "/src/assets/Menu/DSC01144/DSC01144.JPG",
        "category_en": "breakfast, main dishes",
        "category_ar": "فطار, أطباق رئيسية",
        "calories": null,
        "price": 30,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": 10,
        "cookTime_en": 15,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "liver",
            "onions",
            "peppers",
            "tomatoes",
            "oil",
            "spices",
            "whole-grain bread",
            "lemon",
            "tahini"
        ],
        "ingredients_ar": [
            "كبدة",
            "بصل",
            "فلفل",
            "طماطم",
            "زيت",
            "بهارات",
            "خبز أسمر",
            "ليمون",
            "طحينة"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot with bread, lemon, and tahini.",
        "notes_ar": "تقدم ساخنة مع الخبز والليمون والطحينة."
    },
    {
        "id": "13",
        "code": "DSC01275",
        "name_en": "Whole Grain Bread",
        "name_ar": "عيش حب",
        "desc_en": "Bread made from whole grains.",
        "desc_ar": "خبز مصنوع من الحبوب الكاملة.",
        "image": "/src/assets/Menu/DSC01275/DSC01275.JPG",
        "category_en": "bakery",
        "category_ar": "مخبوزات",
        "calories": 69.2,
        "price": 5,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": 0,
        "cookTime_en": null,
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "whole grain flour",
            "water",
            "yeast",
            "salt"
        ],
        "ingredients_ar": [
            "دقيق حبوب كاملة",
            "ماء",
            "خميرة",
            "ملح"
        ],
        "isVegetarian": true,
        "isVegan": true,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Healthy and nutritious bread.",
        "notes_ar": "خبز صحي ومغذي."
    },
    {
        "id": "14",
        "code": "DSC01281",
        "name_en": "Abu El-Khal Falafel",
        "name_ar": "فلافل أبو الخل",
        "desc_en": "4 pieces of falafel served with a variety of delicious sauces and bread.",
        "desc_ar": "4 قطع فلافل تقدم مع أنواع الصوصات الشهية والخبز.",
        "image": "/src/assets/Menu/DSC01281/DSC01281.JPG",
        "category_en": "appetizers, breakfast",
        "category_ar": "مقبلات, فطار",
        "calories": 160,
        "price": 13,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": 15,
        "cookTime_en": "15 minutes (frying)",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "chickpeas",
            "onion",
            "garlic",
            "coriander",
            "parsley",
            "spices",
            "oil for frying",
            "tahini sauce",
            "bread"
        ],
        "ingredients_ar": [
            "حمص",
            "بصل",
            "ثوم",
            "كزبرة",
            "بقدونس",
            "بهارات",
            "زيت للقلي",
            "صوص طحينة",
            "خبز"
        ],
        "isVegetarian": true,
        "isVegan": true,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served as a breakfast dish or appetizer.",
        "notes_ar": "تقدم كوجبة فطار أو مقبلات."
    },
    {
        "id": "15",
        "code": "DSC01425",
        "name_en": "Cream Caramel",
        "name_ar": "توتوه كريم الكراميل",
        "desc_en": "Oven baked cream caramel, served cold with caramelized sugar sauce.",
        "desc_ar": "كريم كراميل مطبوخ في الفرن وتقدم باردة بصوص السكر المكرمل.",
        "image": "/src/assets/Menu/DSC01425/DSC01425.JPG",
        "category_en": "desserts",
        "category_ar": "حلويات",
        "calories": 403,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": null,
        "cookTime_en": null,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "milk",
            "cream",
            "sugar",
            "eggs",
            "vanilla"
        ],
        "ingredients_ar": [
            "حليب",
            "كريمة",
            "سكر",
            "بيض",
            "فانيليا"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": true,
        "servings": 1,
        "notes_en": "Served cold.",
        "notes_ar": "تقدم باردة."
    },
    {
        "id": "16",
        "code": "DSC01446",
        "name_en": "Roqaq Al-Aguat",
        "name_ar": "رقاق الأغوات",
        "desc_en": "Crispy roqaq dough filled with pistachios and cream and served with ice cream.",
        "desc_ar": "عجين رقاق مقرمش محشي بالفستق والقشطة البلدي تقدم مع الآيس كريم.",
        "image": "/src/assets/Menu/DSC01446/DSC01446.JPG",
        "category_en": "desserts",
        "category_ar": "حلويات",
        "calories": 479,
        "price": 25,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": null,
        "cookTime_en": null,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "roqaq dough",
            "pistachios",
            "local cream",
            "ice cream"
        ],
        "ingredients_ar": [
            "عجين رقاق",
            "فستق",
            "قشطة بلدي",
            "آيس كريم"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served with ice cream.",
        "notes_ar": "تقدم مع آيس كريم."
    },
    {
        "id": "17",
        "code": "DSC01493",
        "name_en": "Tarmbeh",
        "name_ar": "طرمبة",
        "desc_en": "Tarmbeh or Balah Al-Sham with ice cream, chocolate and pistachios.",
        "desc_ar": "طرمبة أو بلح الشام بالآيس كريم والشوكولاتة والفستق.",
        "image": "/src/assets/Menu/DSC01493/DSC01493.JPG",
        "category_en": "desserts",
        "category_ar": "حلويات",
        "calories": 455,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": null,
        "cookTime_en": "Frying",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "flour",
            "starch",
            "eggs",
            "oil",
            "syrup",
            "ice cream",
            "chocolate",
            "pistachios"
        ],
        "ingredients_ar": [
            "دقيق",
            "نشا",
            "بيض",
            "زيت",
            "شيرة",
            "آيس كريم",
            "شوكولاتة",
            "فستق حلبي"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served with ice cream, chocolate, and pistachios.",
        "notes_ar": "تقدم مع الآيس كريم والشوكولاتة والفستق."
    },
    {
        "id": "18",
        "code": "DSC01503",
        "name_en": "Um Ali",
        "name_ar": "أم علي",
        "desc_en": "Desert made of roqaq with milk and roasted nuts served hot.",
        "desc_ar": "حلو الرقاق بالحليب مع المكسرات المحمصة وتقدم على طاولة ساخنة.",
        "image": "/src/assets/Menu/DSC01503/DSC01503.JPG",
        "category_en": "desserts",
        "category_ar": "حلويات",
        "calories": 873,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": null,
        "cookTime_en": null,
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "roqaq",
            "milk",
            "cream",
            "sugar",
            "mixed nuts (almonds, pistachios, raisins)",
            "coconut (likely)",
            "vanilla (likely)"
        ],
        "ingredients_ar": [
            "رقاق",
            "حليب",
            "قشطة",
            "سكر",
            "مكسرات مشكلة (لوز، فستق، زبيب)",
            "جوز هند (محتمل)",
            "فانيليا (محتمل)"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot.",
        "notes_ar": "تقدم ساخنة."
    },
    {
        "id": "19",
        "code": "DSC01782",
        "name_en": "Zainab Fermoza (Meat)",
        "name_ar": "فرموزة زينب (لحم)",
        "desc_en": "Layers of thin, crispy dough filled with a special meat mixture and served with Laza.",
        "desc_ar": "طبقات من العجين الرقيق الهش محشوة بخلطة اللحم الخاصة وتقدم مع اللازا.",
        "image": "/src/assets/Menu/DSC01782/DSC01782.JPG",
        "category_en": "appetizers, pastries",
        "category_ar": "مقبلات, معجنات",
        "calories": 454,
        "price": 15,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "20 minutes",
        "cookTime_en": "25 minutes (baking or frying)",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "flour",
            "minced meat",
            "onion",
            "spices",
            "oil",
            "sesame seeds",
            "tomatoes (in Laza)",
            "chili (in Laza)"
        ],
        "ingredients_ar": [
            "دقيق",
            "لحم مفروم",
            "بصل",
            "بهارات",
            "زيت",
            "سمسم",
            "طماطم (في اللازا)",
            "فلفل حار (في اللازا)"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot with spicy Laza sauce.",
        "notes_ar": "تقدم ساخنة مع صلصة اللازا الحارة."
    },
    {
        "id": "20",
        "code": "DSC01815",
        "name_en": "White Cheese Rolls",
        "name_ar": "سمبوسك سجائر الجبنة البيضاء",
        "desc_en": "4 pieces of rolls filled with Baladi cheese.",
        "desc_ar": "٤ قطع عجين رول محشوة بالجبنة البلدي.",
        "image": "/src/assets/Menu/DSC01815/DSC01815.JPG",
        "category_en": "appetizers, pastries",
        "category_ar": "مقبلات, معجنات",
        "calories": 332,
        "price": 15,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "15 minutes",
        "cookTime_en": "20 minutes (frying or baking)",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "sambousek pastry",
            "Baladi cheese",
            "parsley",
            "oil for frying/baking",
            "tomatoes (in sauce)",
            "peppers (in sauce)"
        ],
        "ingredients_ar": [
            "عجينة سمبوسك",
            "جبنة بلدي",
            "بقدونس",
            "زيت للقلي/للخبز",
            "طماطم (في الصلصة)",
            "فلفل (في الصلصة)"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot with sauce.",
        "notes_ar": "تقدم ساخنة مع صلصة."
    },
    {
        "id": "21",
        "code": "DSC02166",
        "name_en": "Rolled Borek",
        "name_ar": "بريك ملفوف",
        "desc_en": "A traditional pastry from Madinah, featuring flaky dough layers filled with a savory mixture, rolled and baked to perfection.",
        "desc_ar": "معجنات تقليدية من المدينة، تتكون من طبقات عجين هشة محشوة بخليط لذيذ، ملفوفة ومخبوزة حتى الكمال.",
        "image": "/src/assets/Menu/DSC02166/DSC02166.JPG",
        "category_en": "pastries, breakfast",
        "category_ar": "معجنات, فطار",
        "calories": 265,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "20 minutes",
        "cookTime_en": "30-40 minutes (baking)",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "flour",
            "butter/oil",
            "milk/yogurt",
            "cheese (likely)",
            "minced meat (likely)",
            "egg (for glazing)",
            "parsley"
        ],
        "ingredients_ar": [
            "دقيق",
            "زبدة/زيت",
            "حليب/زبادي",
            "جبنة (محتمل)",
            "لحم مفروم (محتمل)",
            "بيضة (للوجه)",
            "بقدونس"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "A delicious and nutritious pastry.",
        "notes_ar": "معجنات شهية ومغذية."
    },
    {
        "id": "22",
        "code": "DSC01863",
        "name_en": "Triangular Meat Samosa",
        "name_ar": "سمبوسك مثلث اللحم",
        "desc_en": "4 triangular pieces of meat stuffed with meat and eggs in the Madini mixture.",
        "desc_ar": "٤ قطع مثلث لحم محشوة باللحم والبيض بالخلطة المدينية.",
        "image": "/src/assets/Menu/DSC01863/DSC01863.JPG",
        "category_en": "appetizers, pastries",
        "category_ar": "مقبلات, معجنات",
        "calories": 355,
        "price": 15,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "20 minutes",
        "cookTime_en": "20 minutes (frying or baking)",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "sambousek pastry",
            "minced meat",
            "eggs",
            "onion",
            "Madini spices",
            "oil for frying/baking",
            "tomatoes (in sauce)",
            "peppers (in sauce)"
        ],
        "ingredients_ar": [
            "عجينة سمبوسك",
            "لحم مفروم",
            "بيض",
            "بصل",
            "بهارات مدينية",
            "زيت للقلي/للخبز",
            "طماطم (في الصلصة)",
            "فلفل (في الصلصة)"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Samosa with a special Madini mixture.",
        "notes_ar": "سمبوسك بالخلطة المدينية المميزة."
    },
    {
        "id": "23",
        "code": "DSC02135",
        "name_en": "White Cheese with Tomatoes and Mint",
        "name_ar": "جبنة بيضاء وطماطم ونعناع",
        "desc_en": "Sandwich filled with white cheese, tomato slices, and fresh mint leaves.",
        "desc_ar": "ساندوتش محشو بجبنة بيضاء وشرائح طماطم وأوراق نعناع طازجة.",
        "image": "/src/assets/Menu/DSC02135/DSC02135.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 15,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "غير محدد",
        "cookTime_en": "0",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "simit/bagel bread",
            "white cheese",
            "tomatoes",
            "mint"
        ],
        "ingredients_ar": [
            "خبز سميت/بيجل",
            "جبنة بيضاء",
            "طماطم",
            "نعناع"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served as a light meal or breakfast.",
        "notes_ar": "يقدم كوجبة خفيفة أو فطار."
    },
    {
        "id": "24",
        "code": "DSC02142",
        "name_en": "Fattout of Souq Al-Shamiya",
        "name_ar": "فتوت سوق الشامية",
        "desc_en": "Halloumi cheese with sun-dried tomatoes stuffed in fattout bread, with black seeds and more.",
        "desc_ar": "جبنة حلوم بالطماطم المجففة محشية في خبز الفتوت وجبة بالبركة زيت الزيتون وتقدم محمصة.",
        "image": "/src/assets/Menu/DSC02142/DSC02142.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 10,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": "غير محدد",
        "cookTime_en": "غير محدد",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "fattout bread",
            "halloumi cheese",
            "sun-dried tomatoes",
            "olive oil",
            "black olives",
            "black seeds (likely sesame)"
        ],
        "ingredients_ar": [
            "خبز فتوت",
            "جبنة حلوم",
            "طماطم مجففة",
            "زيت زيتون",
            "زيتون أسود",
            "سمسم (محتمل)"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served toasted as a light meal.",
        "notes_ar": "تقدم محمصة كوجبة خفيفة."
    },
    {
        "id": "25",
        "code": "DSC02150",
        "name_en": "Cheese Liver",
        "name_ar": "كبدة بالجبنة",
        "desc_en": "Fresh liver with hob bread and cheese cups.",
        "desc_ar": "الكبدة الطازجة بعيش الحب والجبنة كاسات.",
        "image": "/src/assets/Menu/DSC02150/DSC02150.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "غير محدد",
        "cookTime_en": "غير محدد",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "hob bread",
            "liver",
            "cheese cups",
            "tomatoes",
            "pepper",
            "lemon",
            "arugula"
        ],
        "ingredients_ar": [
            "عيش حب",
            "كبدة",
            "جبنة كاسات",
            "طماطم",
            "فلفل",
            "ليمون",
            "جرجير"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot.",
        "notes_ar": "يقدم ساخنًا."
    },
    {
        "id": "26",
        "code": "DSC02159",
        "name_en": "Grilled Samoli",
        "name_ar": "صامولي شواية",
        "desc_en": "Grilled chicken fillet in samoli bread served with tahini sauce.",
        "desc_ar": "قطع من الدجاج الشواية المخلية محشية داخل خبز الصامولي الشهي وتقدم بصوص الطحينة والدقس.",
        "image": "/src/assets/Menu/DSC02159/DSC02159.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 10,
        "rating": 0,
        "available": true,
        "trendy": true,
        "prepTime": "غير محدد",
        "cookTime_en": "غير محدد",
        "difficulty_en": "medium",
        "difficulty_ar": "متوسط",
        "ingredients_en": [
            "samoli bread",
            "grilled chicken",
            "tahini sauce",
            "daqoos"
        ],
        "ingredients_ar": [
            "صامولي",
            "دجاج مشوي",
            "طحينة",
            "دقس"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served hot with tahini and daqoos sauce.",
        "notes_ar": "يقدم ساخنًا مع صوص الطحينة والدقس."
    },
    {
        "id": "27",
        "code": "DSC02166",
        "name_en": "Fries Samoli Sandwich",
        "name_ar": "ساندوتش صامولي بالبطاطس المقلية",
        "desc_en": "Long samoli bread sandwich filled with french fries, served with three types of sauce.",
        "desc_ar": "ساندوتش صامولي طويل محشو بالبطاطس المقلية، يقدم مع ثلاثة أنواع من الصوص.",
        "image": "/src/assets/Menu/DSC02166/DSC02166.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 10,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "غير محدد",
        "cookTime_en": "غير محدد",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "samoli bread",
            "french fries",
            "ketchup sauce",
            "mayonnaise sauce",
            "brown sauce"
        ],
        "ingredients_ar": [
            "صامولي",
            "بطاطس مقلية",
            "صوص كاتشب",
            "صوص مايونيز",
            "صوص بني"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served as a quick meal.",
        "notes_ar": "يقدم كوجبة سريعة."
    },
    {
        "id": "28",
        "code": "DSC02181",
        "name_en": "Mutton Head Sandwich",
        "name_ar": "ساندويتش لحمة راس",
        "desc_en": "Grilled mutton head beef with dried spices in grain bread and served with tahini sauce, dakos, and vinaigrette.",
        "desc_ar": "قطع من لحم الرأس المشوي بالبهارات الجافة ومحشية في خبز البر وتقدم مع صوص الطحينة والخل والدقس.",
        "image": "/src/assets/Menu/DSC02181/DSC02181.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندوتشات",
        "calories": 0,
        "price": 20,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "غير محدد",
        "cookTime_en": "غير محدد",
        "difficulty_en": "medium to hard",
        "difficulty_ar": "متوسط إلى صعب",
        "ingredients_en": [
            "grain bread/local bread",
            "mutton head",
            "dried spices",
            "tahini sauce",
            "vinegar",
            "daqoos"
        ],
        "ingredients_ar": [
            "خبز أسمر/بلدي",
            "لحم رأس",
            "بهارات جافة",
            "طحينة",
            "خل",
            "دقس"
        ],
        "isVegetarian": false,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Traditional dish.",
        "notes_ar": "طبق تقليدي."
    },
    {
        "id": "29",
        "code": "DSC02189",
        "name_en": "City Salad Sandwich",
        "name_ar": "ساندويتش سلات المدينة",
        "desc_en": "Sandwich filled with a variety of city salads.",
        "desc_ar": "ساندويتش محشو بمجموعة متنوعة من سلطات المدينة.",
        "image": "/src/assets/Menu/DSC02189/DSC02189.JPG",
        "category_en": "sandwiches",
        "category_ar": "ساندويتشات",
        "calories": 0,
        "price": 25,
        "rating": 0,
        "available": true,
        "trendy": false,
        "prepTime": "غير محدد",
        "cookTime_en": "0",
        "difficulty_en": "easy",
        "difficulty_ar": "سهل",
        "ingredients_en": [
            "grain bread/local bread",
            "assorted salads (likely: lettuce, tomatoes, cucumbers, onions, mayonnaise/tahini)"
        ],
        "ingredients_ar": [
            "خبز أسمر/بلدي",
            "سلطات متنوعة (محتمل: خس, طماطم, خيار, بصل, مايونيز/طحينة)"
        ],
        "isVegetarian": true,
        "isVegan": false,
        "isGlutenFree": false,
        "servings": 1,
        "notes_en": "Served with potato chips and sauce.",
        "notes_ar": "يقدم مع بطاطس شيبس وصوص."
    }

];

export default productsData;