import img1 from "../assets/Menu/DSC00764/DSC00764.JPG";
import img2 from "../assets/Menu/DSC00840/DSC00840.JPG";
import img3 from "../assets/Menu/DSC00865/DSC00865.JPG";
import img4 from "../assets/Menu/DSC00875/DSC00875.JPG";
import img5 from "../assets/Menu/DSC00965/DSC00965.JPG";
import img6 from "../assets/Menu/DSC00973/DSC00973.JPG";
import img7 from "../assets/Menu/DSC00993/DSC00993.JPG";
import img8 from "../assets/Menu/DSC01010/DSC01010.JPG";
import img9 from "../assets/Menu/DSC01012/DSC01012.JPG";
import img10 from "../assets/Menu/DSC01024/DSC01024.JPG";
import img11 from "../assets/Menu//DSC01141/DSC01141.JPG";
import img12 from "../assets/Menu/DSC01144/DSC01144.JPG";
import img13 from "../assets/Menu/DSC01275/DSC01275.JPG";
import img14 from "../assets/Menu/DSC01281/DSC01281.JPG";
import img15 from "../assets/Menu/DSC01425/DSC01425.JPG";
import img16 from "../assets/Menu/DSC01446/DSC01446.JPG";
import img17 from "../assets/Menu/DSC01493/DSC01493.JPG";
import img18 from "../assets/Menu/DSC01503/DSC01503.JPG";
import img19 from "../assets/Menu/DSC01782/DSC01782.JPG";
import img20 from "../assets/Menu/DSC01815/DSC01815.JPG";
import img21 from "../assets/Menu/DSC01852/DSC01852.JPG";
import img22 from "../assets/Menu/DSC01863/DSC01863.JPG";
import img23 from "../assets/Menu/DSC02135/DSC02135.JPG";
import img24 from "../assets/Menu/DSC02142/DSC02142.JPG";
import img25 from "../assets/Menu/DSC02150/DSC02150.JPG";
import img26 from "../assets/Menu/DSC02159/DSC02159.JPG";
import img27 from "../assets/Menu/DSC02166/DSC02166.JPG";
import img28 from "../assets/Menu/DSC02181/DSC02181.JPG";
import img29 from "../assets/Menu/DSC01791/DSC01791.JPG";
import img30 from "../assets/Menu/DSC01232/DSC01232.JPG";
import img31 from "../assets/Menu/DSC01866/DSC01866.JPG";
import img32 from "../assets/Menu/DSC01863/DSC01863.JPG";
import img33 from "../assets/Menu/DSC01937/DSC01937.JPG";
import img34 from "../assets/Menu/DSC01902/DSC01902.JPG";
import img35 from "../assets/Menu/DSC01929/DSC01929.JPG";
import img36 from "../assets/Menu/DSC01885/DSC01885.JPG";
import img37 from "../assets/Menu/DSC01921/DSC01921.JPG";
import img38 from "../assets/Menu/DSC01954/DSC01954.JPG";
import img39 from "../assets/Menu/DSC01946/DSC01946.JPG";

const productsData = [
  {
    id: "1",
    code: "DSC00764",
    name_en: "Salty Halawa",
    name_ar: "حلاوة طحينية مالحة",
    desc_en: "Halawa mixed with cheese and oil.",
    desc_ar: "حلاوة طحينية ممزوجة بالجبنة والزيت.",
    image: img1,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 136,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 5,
    cookTime_en: 0,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["halawa", "white cheese", "olive oil"],
    ingredients_ar: ["حلاوة طحينية", "جبنة بيضاء", "زيت زيتون"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "A unique mix of sweetness and saltiness.",
    notes_ar: "مزيج فريد من الحلاوة والملوحة.",
  },
  {
    id: "2",
    code: "DSC00840",
    name_en: "Olives",
    name_ar: "زيتون",
    desc_en: "A selection of green and black olives pickled in To'mah jars.",
    desc_ar: "تشكيلة من الزيتون الأخضر والأسود والمخلل في برطمانات طعمة.",
    image: img2,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 141,
    price: 9,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 0,
    cookTime_en: 0,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "green olives",
      "black olives",
      "water",
      "salt",
      "preservatives",
    ],
    ingredients_ar: ["زيتون أخضر", "زيتون أسود", "ماء", "ملح", "مواد حافظة"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Pickled in To'mah jars.",
    notes_ar: "مخلل في برطمانات طعمة.",
  },
  {
    id: "3",
    code: "DSC00865",
    name_en: "Labneh with Beetroot",
    name_ar: "لبنة بالبنجر",
    desc_en: "Labneh with a very special beetroot mix.",
    desc_ar: "لبنة بخلطة مميزة جدا من البنجر.",
    image: img3,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 249,
    price: 13,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 10,
    cookTime_en: 0,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "labneh",
      "beetroot",
      "garlic",
      "mint",
      "olive oil",
      "salt",
    ],
    ingredients_ar: ["لبنة", "بنجر", "ثوم", "نعناع", "زيت زيتون", "ملح"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Labneh with a refreshing and unique flavor.",
    notes_ar: "لبنة بنكهة منعشة ومميزة.",
  },
  {
    id: "4",
    code: "DSC00875",
    name_en: "Honey and Clotted Cream",
    name_ar: "عسل وقشطة",
    desc_en: "Qeshta and honey mix with pistachio.",
    desc_ar: "خلطة العسل والقشطة ورشة الفستق.",
    image: img4,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 328,
    price: 17,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 5,
    cookTime_en: 0,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["clotted cream (qeshta)", "honey", "pistachios"],
    ingredients_ar: ["قشطة بلدي", "عسل", "فستق حلبي"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Served as a breakfast dish or light dessert.",
    notes_ar: "تقدم كوجبة فطار أو حلوى خفيفة.",
  },
  {
    id: "5",
    code: "DSC00965",
    name_en: "Labneh",
    name_ar: "لبنة سادة",
    desc_en: "Plain Labneh for our loved ones.",
    desc_ar: "لبنة سادة للحبايب.",
    image: img5,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 332,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 5,
    cookTime_en: 0,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["labneh", "olive oil", "mint", "salt"],
    ingredients_ar: ["لبنة", "زيت زيتون", "نعناع", "ملح"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Served as an appetizer or part of breakfast.",
    notes_ar: "تقدم كفاتح للشهية أو جزء من وجبة الإفطار.",
  },
  {
    id: "6",
    code: "DSC00973",
    name_en: "Yellow Cheese with Eggplant",
    name_ar: "جبنة صفراء بالباذنجان",
    desc_en:
      "A blend of cheddar cheese and fried eggplant with an irresistible sauce.",
    desc_ar: "خليط الجبنة التشيدر والباذنجان المقلي بصوص لا يقاوم.",
    image: img6,
    category_en: "Breakfast/Nawashif Ta'ameh Set",
    category_ar: "الفطور/مجموعة نواشف طعمة",
    calories: 110,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 15,
    cookTime_en: 10,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "cheddar cheese",
      "eggplant",
      "frying oil",
      "parsley",
      "mint",
      "garlic",
      "olive oil",
      "red pepper",
      "salt",
    ],
    ingredients_ar: [
      "جبنة تشيدر",
      "باذنجان",
      "زيت للقلي",
      "بقدونس",
      "نعناع",
      "ثوم",
      "زيت زيتون",
      "فلفل أحمر",
      "ملح",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Served as a side dish or appetizer.",
    notes_ar: "يقدم كطبق جانبي أو مقبلات.",
  },
  {
    id: "7",
    code: "DSC00993",
    name_en: "To'mah Shakshuka",
    name_ar: "شكشوكة طعمة ",
    desc_en: "The authentic Hejazi Shakshuka",
    desc_ar: "الشكشوكة الحجازية الأصيلة",
    image: img7,
    category_en: "Breakfast/Egg Selections",
    category_ar: "الفطور/مختارات البيض",
    calories: null,
    price: 17,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 10,
    cookTime_en: 20,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "eggs",
      "tomatoes",
      "peppers",
      "onions",
      "garlic",
      "Hejazi spices",
      "oil",
    ],
    ingredients_ar: [
      "بيض",
      "طماطم",
      "فلفل",
      "بصل",
      "ثوم",
      "بهارات حجازية",
      "زيت",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Authentic and delicious Hejazi shakshuka.",
    notes_ar: "شكشوكة حجازية أصيلة ولذيذة.",
  },
  {
    id: "8",
    code: "DSC01010",
    name_en: "To'mah Eggs",
    name_ar: "بيض طعمة",
    desc_en:
      "Eggs with vegetables and melted cheese, prepared in the chef's special way.",
    desc_ar: "بيض بالخضار والجبنة المطبوخة بطريقة الشيف الخاصة.",
    image: img8,
    category_en: "Breakfast/Egg Selections",
    category_ar: "الفطور/مختارات البيض",
    calories: null,
    price: 23,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 10,
    cookTime_en: 15,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "eggs",
      "tomatoes",
      "onions",
      "peppers",
      "cheese",
      "cream/qeshta",
      "spices",
    ],
    ingredients_ar: [
      "بيض",
      "طماطم",
      "بصل",
      "فلفل",
      "جبنة",
      "قشطة/كريمة",
      "بهارات",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Special egg dish prepared in the chef's way.",
    notes_ar: "طبق بيض مميز بطريقة الشيف.",
  },
  {
    id: "9",
    code: "DSC01012",
    name_en: "Butter Eggs",
    name_ar: "بيض بالزبدة",
    desc_en:
      "Egg fried with butter, salt, and Madinah's special Dukkah spice mix.",
    desc_ar: "حلقات البيض مشوحة بالزبدة والملح ودقة المدينة المميزة.",
    image: img9,
    category_en: "Breakfast/Egg Selections",
    category_ar: "الفطور/مختارات البيض",
    calories: null,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 5,
    cookTime_en: 10,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["eggs", "butter", "salt", "Madinah's Dukkah spice mix"],
    ingredients_ar: ["بيض", "زبدة", "ملح", "دقة المدينة"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Quick and delicious breakfast dish.",
    notes_ar: "طبق فطار سريع ولذيذ.",
  },
  {
    id: "10",
    code: "DSC01024",
    name_en: "Fried Eggs",
    name_ar: "بيض مقلي",
    desc_en: "For the good ones.",
    desc_ar: "بيض الطيبين.",
    image: img10,
    category_en: "Breakfast/Egg Selections",
    category_ar: "الفطور/مختارات البيض",
    calories: null,
    price: 17,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 2,
    cookTime_en: 5,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "eggs",
      "oil/butter",
      "salt",
      "pepper",
      "parsley/coriander (for garnish)",
    ],
    ingredients_ar: [
      "بيض",
      "زيت/زبدة",
      "ملح",
      "فلفل",
      "بقدونس/كزبرة (للتزيين)",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Simple and delicious breakfast dish.",
    notes_ar: "طبق فطار بسيط ولذيذ.",
  },
  {
    id: "11",
    code: "DSC01141",
    name_en: "Hawah Fattah",
    name_ar: "فتة هوا",
    desc_en: "Fattah with whole-grain bread in chicken broth.",
    desc_ar: "فتة عيش حب بمرقة الدجاج.",
    image: img11,
    category_en: "breakfast, main dishes",
    category_ar: "فطار, أطباق رئيسية",
    calories: null,
    price: 30,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 15,
    cookTime_en: 25,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "whole-grain bread",
      "chicken broth",
      "yogurt/tahini",
      "parsley",
      "pine nuts/almonds",
      "garlic (likely)",
      "ghee (likely)",
    ],
    ingredients_ar: [
      "خبز أسمر/حبوب كاملة",
      "مرقة دجاج",
      "زبادي/طحينة",
      "بقدونس",
      "صنوبر/لوز",
      "ثوم (محتمل)",
      "سمن (محتمل)",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Delicious fattah dish with chicken broth.",
    notes_ar: "طبق فتة شهي بمرقة الدجاج.",
  },
  {
    id: "12",
    code: "DSC01144",
    name_en: "Cook's Market Liver",
    name_ar: "كبدة سوق الطباخة",
    desc_en:
      "Liver fried with vegetables over high heat, served with whole-grain bread, lemon wedges, and tahini.",
    desc_ar:
      "كبدة مشوحة بالخضار على نار عالية وتقدم بخبز أسمر وقطع الليمون والطحينة.",
    image: img12,
    category_en: "Breakfast/Chef's Breakfast",
    category_ar: "فطور/فطور الطباخة",
    calories: null,
    price: 30,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 10,
    cookTime_en: 15,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "liver",
      "onions",
      "peppers",
      "tomatoes",
      "oil",
      "spices",
      "whole-grain bread",
      "lemon",
      "tahini",
    ],
    ingredients_ar: [
      "كبدة",
      "بصل",
      "فلفل",
      "طماطم",
      "زيت",
      "بهارات",
      "خبز أسمر",
      "ليمون",
      "طحينة",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot with bread, lemon, and tahini.",
    notes_ar: "تقدم ساخنة مع الخبز والليمون والطحينة.",
  },
  {
    id: "13",
    code: "DSC01275",
    name_en: "Whole Grain Bread",
    name_ar: "عيش حب",
    desc_en: "Bread made from whole grains.",
    desc_ar: "خبز مصنوع من الحبوب الكاملة.",
    image: img13,
    category_en: "fresh baked goods",
    category_ar: " المخبوزات الطازة ",
    calories: 69.2,
    price: 5,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: 0,
    cookTime_en: null,
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["whole grain flour", "water", "yeast", "salt"],
    ingredients_ar: ["دقيق حبوب كاملة", "ماء", "خميرة", "ملح"],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Healthy and nutritious bread.",
    notes_ar: "خبز صحي ومغذي.",
  },
  {
    id: "14",
    code: "DSC01281",
    name_en: "Abu El-Khal Falafel",
    name_ar: "فلافل أبو الخل",
    desc_en:
      "4 pieces of falafel served with a variety of delicious sauces and bread.",
    desc_ar: "4 قطع فلافل تقدم مع أنواع الصوصات الشهية والخبز.",
    image: img14,
    category_en: "Breakfast/Snack",
    category_ar: "فطور/تصبيرة",
    calories: 160,
    price: 13,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: 15,
    cookTime_en: "15 minutes (frying)",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "chickpeas",
      "onion",
      "garlic",
      "coriander",
      "parsley",
      "spices",
      "oil for frying",
      "tahini sauce",
      "bread",
    ],
    ingredients_ar: [
      "حمص",
      "بصل",
      "ثوم",
      "كزبرة",
      "بقدونس",
      "بهارات",
      "زيت للقلي",
      "صوص طحينة",
      "خبز",
    ],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served as a breakfast dish or appetizer.",
    notes_ar: "تقدم كوجبة فطار أو مقبلات.",
  },
  {
    id: "15",
    code: "DSC01425",
    name_en: "Cream Caramel",
    name_ar: "توتوه كريم الكراميل",
    desc_en:
      "Oven baked cream caramel, served cold with caramelized sugar sauce.",
    desc_ar: "كريم كراميل مطبوخ في الفرن وتقدم باردة بصوص السكر المكرمل.",
    image: img15,
    category_en: "Desserts",
    category_ar: "حلويات",
    calories: 403,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: null,
    cookTime_en: null,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: ["milk", "cream", "sugar", "eggs", "vanilla"],
    ingredients_ar: ["حليب", "كريمة", "سكر", "بيض", "فانيليا"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: true,
    servings: 1,
    notes_en: "Served cold.",
    notes_ar: "تقدم باردة.",
  },
  {
    id: "16",
    code: "DSC01446",
    name_en: "Roqaq Al-Aguat",
    name_ar: "رقاق الأغوات",
    desc_en:
      "Crispy roqaq dough filled with pistachios and cream and served with ice cream.",
    desc_ar: "عجين رقاق مقرمش محشي بالفستق والقشطة البلدي تقدم مع الآيس كريم.",
    image: img16,
    category_en: "Desserts",
    category_ar: "حلويات",
    calories: 479,
    price: 25,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: null,
    cookTime_en: null,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: ["roqaq dough", "pistachios", "local cream", "ice cream"],
    ingredients_ar: ["عجين رقاق", "فستق", "قشطة بلدي", "آيس كريم"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served with ice cream.",
    notes_ar: "تقدم مع آيس كريم.",
  },
  {
    id: "17",
    code: "DSC01493",
    name_en: "Tarmbeh",
    name_ar: "طرمبة",
    desc_en:
      "Tarmbeh or Balah Al-Sham with ice cream, chocolate and pistachios.",
    desc_ar: "طرمبة أو بلح الشام بالآيس كريم والشوكولاتة والفستق.",
    image: img17,
    category_en: "Desserts",
    category_ar: "حلويات",
    calories: 455,
    price: 20,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: null,
    cookTime_en: "Frying",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "flour",
      "starch",
      "eggs",
      "oil",
      "syrup",
      "ice cream",
      "chocolate",
      "pistachios",
    ],
    ingredients_ar: [
      "دقيق",
      "نشا",
      "بيض",
      "زيت",
      "شيرة",
      "آيس كريم",
      "شوكولاتة",
      "فستق حلبي",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served with ice cream, chocolate, and pistachios.",
    notes_ar: "تقدم مع الآيس كريم والشوكولاتة والفستق.",
  },
  {
    id: "18",
    code: "DSC01503",
    name_en: "Um Ali",
    name_ar: "أم علي",
    desc_en: "Desert made of roqaq with milk and roasted nuts served hot.",
    desc_ar: "حلو الرقاق بالحليب مع المكسرات المحمصة وتقدم على طاولة ساخنة.",
    image: img18,
    category_en: "Desserts",
    category_ar: "حلويات",
    calories: 873,
    price: 20,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: null,
    cookTime_en: null,
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "roqaq",
      "milk",
      "cream",
      "sugar",
      "mixed nuts (almonds, pistachios, raisins)",
      "coconut (likely)",
      "vanilla (likely)",
    ],
    ingredients_ar: [
      "رقاق",
      "حليب",
      "قشطة",
      "سكر",
      "مكسرات مشكلة (لوز، فستق، زبيب)",
      "جوز هند (محتمل)",
      "فانيليا (محتمل)",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot.",
    notes_ar: "تقدم ساخنة.",
  },
  {
    id: "19",
    code: "DSC01782",
    name_en: "Zainab Fermoza (Meat)",
    name_ar: "فرموزة زينب (لحم)",
    desc_en:
      "Layers of thin, crispy dough filled with a special meat mixture and served with Laza.",
    desc_ar:
      "طبقات من العجين الرقيق الهش محشوة بخلطة اللحم الخاصة وتقدم مع اللازا.",
    image: img19,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 454,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "20 minutes",
    cookTime_en: "25 minutes (baking or frying)",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "flour",
      "minced meat",
      "onion",
      "spices",
      "oil",
      "sesame seeds",
      "tomatoes (in Laza)",
      "chili (in Laza)",
    ],
    ingredients_ar: [
      "دقيق",
      "لحم مفروم",
      "بصل",
      "بهارات",
      "زيت",
      "سمسم",
      "طماطم (في اللازا)",
      "فلفل حار (في اللازا)",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot with spicy Laza sauce.",
    notes_ar: "تقدم ساخنة مع صلصة اللازا الحارة.",
  },
  {
    id: "20",
    code: "DSC01815",
    name_en: "White Cheese Rolls",
    name_ar: "سمبوسك سجائر الجبنة البيضاء",
    desc_en: "4 pieces of rolls filled with Baladi cheese.",
    desc_ar: "٤ قطع عجين رول محشوة بالجبنة البلدي.",
    image: img20,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 332,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "15 minutes",
    cookTime_en: "20 minutes (frying or baking)",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "sambousek pastry",
      "Baladi cheese",
      "parsley",
      "oil for frying/baking",
      "tomatoes (in sauce)",
      "peppers (in sauce)",
    ],
    ingredients_ar: [
      "عجينة سمبوسك",
      "جبنة بلدي",
      "بقدونس",
      "زيت للقلي/للخبز",
      "طماطم (في الصلصة)",
      "فلفل (في الصلصة)",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot with sauce.",
    notes_ar: "تقدم ساخنة مع صلصة.",
  },
  {
    id: "RolledBorek",
    code: "DSC01852",
    name_en: "Rolled Borek",
    name_ar: "بريك ملفوف",
    desc_en:
      "A traditional pastry from Madinah, featuring flaky dough layers filled with a savory mixture, rolled and baked to perfection.",
    desc_ar:
      "معجنات تقليدية من المدينة، تتكون من طبقات عجين هشة محشوة بخليط لذيذ، ملفوفة ومخبوزة حتى الكمال.",
    image: img21,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 265,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "20 minutes",
    cookTime_en: "30-40 minutes (baking)",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "flour",
      "butter/oil",
      "milk/yogurt",
      "cheese (likely)",
      "minced meat (likely)",
      "egg (for glazing)",
      "parsley",
    ],
    ingredients_ar: [
      "دقيق",
      "زبدة/زيت",
      "حليب/زبادي",
      "جبنة (محتمل)",
      "لحم مفروم (محتمل)",
      "بيضة (للوجه)",
      "بقدونس",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "A delicious and nutritious pastry.",
    notes_ar: "معجنات شهية ومغذية.",
  },
  {
    id: "22",
    code: "DSC01863",
    name_en: "Triangular Meat Samosa",
    name_ar: "سمبوسك مثلث اللحم",
    desc_en:
      "4 triangular pieces of meat stuffed with meat and eggs in the Madini mixture.",
    desc_ar: "٤ قطع مثلث لحم محشوة باللحم والبيض بالخلطة المدينية.",
    image: img22,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 355,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "20 minutes",
    cookTime_en: "20 minutes (frying or baking)",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "sambousek pastry",
      "minced meat",
      "eggs",
      "onion",
      "Madini spices",
      "oil for frying/baking",
      "tomatoes (in sauce)",
      "peppers (in sauce)",
    ],
    ingredients_ar: [
      "عجينة سمبوسك",
      "لحم مفروم",
      "بيض",
      "بصل",
      "بهارات مدينية",
      "زيت للقلي/للخبز",
      "طماطم (في الصلصة)",
      "فلفل (في الصلصة)",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Samosa with a special Madini mixture.",
    notes_ar: "سمبوسك بالخلطة المدينية المميزة.",
  },
  {
    id: "23",
    code: "DSC02135",
    name_en: "White Cheese with Tomatoes and Mint",
    name_ar: "جبنة بيضاء وطماطم ونعناع",
    desc_en:
      "Sandwich filled with white cheese, tomato slices, and fresh mint leaves.",
    desc_ar: "ساندوتش محشو بجبنة بيضاء وشرائح طماطم وأوراق نعناع طازجة.",
    image: img23,
    category_en: "sandwiches",
    category_ar: "ساندوتشات",
    calories: 0,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "0",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: ["simit/bagel bread", "white cheese", "tomatoes", "mint"],
    ingredients_ar: ["خبز سميت/بيجل", "جبنة بيضاء", "طماطم", "نعناع"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served as a light meal or breakfast.",
    notes_ar: "يقدم كوجبة خفيفة أو فطار.",
  },
  {
    id: "24",
    code: "DSC02142",
    name_en: "Fattout of Souq Al-Shamiya",
    name_ar: "فتوت سوق الشامية",
    desc_en:
      "Halloumi cheese with sun-dried tomatoes stuffed in fattout bread, with black seeds and more.",
    desc_ar:
      "جبنة حلوم بالطماطم المجففة محشية في خبز الفتوت وجبة بالبركة زيت الزيتون وتقدم محمصة.",
    image: img24,
    category_en: "sandwiches",
    category_ar: "ساندوتشات",
    calories: 0,
    price: 10,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "fattout bread",
      "halloumi cheese",
      "sun-dried tomatoes",
      "olive oil",
      "black olives",
      "black seeds (likely sesame)",
    ],
    ingredients_ar: [
      "خبز فتوت",
      "جبنة حلوم",
      "طماطم مجففة",
      "زيت زيتون",
      "زيتون أسود",
      "سمسم (محتمل)",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served toasted as a light meal.",
    notes_ar: "تقدم محمصة كوجبة خفيفة.",
  },
  {
    id: "25",
    code: "DSC02150",
    name_en: "Cheese Liver",
    name_ar: "كبدة بالجبنة",
    desc_en: "Fresh liver with hob bread and cheese cups.",
    desc_ar: "الكبدة الطازجة بعيش الحب والجبنة كاسات.",
    image: img25,
    category_en: "wheat bread sandwich",
    category_ar: "ساندوتش عيش الحب",
    calories: 0,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "hob bread",
      "liver",
      "cheese cups",
      "tomatoes",
      "pepper",
      "lemon",
      "arugula",
    ],
    ingredients_ar: [
      "عيش حب",
      "كبدة",
      "جبنة كاسات",
      "طماطم",
      "فلفل",
      "ليمون",
      "جرجير",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot.",
    notes_ar: "يقدم ساخنًا.",
  },
  {
    id: "26",
    code: "DSC02159",
    name_en: "Grilled Samoli",
    name_ar: "صامولي شواية",
    desc_en: "Grilled chicken fillet in samoli bread served with tahini sauce.",
    desc_ar:
      "قطع من الدجاج الشواية المخلية محشية داخل خبز الصامولي الشهي وتقدم بصوص الطحينة والدقس.",
    image: img26,
    category_en: "sandwiches",
    category_ar: "ساندوتشات",
    calories: 0,
    price: 10,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "samoli bread",
      "grilled chicken",
      "tahini sauce",
      "daqoos",
    ],
    ingredients_ar: ["صامولي", "دجاج مشوي", "طحينة", "دقس"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served hot with tahini and daqoos sauce.",
    notes_ar: "يقدم ساخنًا مع صوص الطحينة والدقس.",
  },
  {
    id: "27",
    code: "DSC02166",
    name_en: "Fries Samoli Sandwich",
    name_ar: "ساندوتش صامولي بالبطاطس المقلية",
    desc_en:
      "Long samoli bread sandwich filled with french fries, served with three types of sauce.",
    desc_ar:
      "ساندوتش صامولي طويل محشو بالبطاطس المقلية، يقدم مع ثلاثة أنواع من الصوص.",
    image: img27,
    category_en: "sandwiches",
    category_ar: "ساندوتشات",
    calories: 0,
    price: 10,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "samoli bread",
      "french fries",
      "ketchup sauce",
      "mayonnaise sauce",
      "brown sauce",
    ],
    ingredients_ar: [
      "صامولي",
      "بطاطس مقلية",
      "صوص كاتشب",
      "صوص مايونيز",
      "صوص بني",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served as a quick meal.",
    notes_ar: "يقدم كوجبة سريعة.",
  },
  {
    id: "28",
    code: "DSC02181",
    name_en: "Mutton Head Sandwich",
    name_ar: "ساندويتش لحمة راس",
    desc_en:
      "Grilled mutton head beef with dried spices in grain bread and served with tahini sauce, dakos, and vinaigrette.",
    desc_ar:
      "قطع من لحم الرأس المشوي بالبهارات الجافة ومحشية في خبز البر وتقدم مع صوص الطحينة والخل والدقس.",
    image: img28,
    category_en: "wheat bread sandwich",
    category_ar: "ساندوتش عيش الحب",
    calories: 0,
    price: 20,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium to hard",
    difficulty_ar: "متوسط إلى صعب",
    ingredients_en: [
      "grain bread/local bread",
      "mutton head",
      "dried spices",
      "tahini sauce",
      "vinegar",
      "daqoos",
    ],
    ingredients_ar: [
      "خبز أسمر/بلدي",
      "لحم رأس",
      "بهارات جافة",
      "طحينة",
      "خل",
      "دقس",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Traditional dish.",
    notes_ar: "طبق تقليدي.",
  },
  {
    id: "29",
    code: "DSC02189",
    name_en: "City Salad Sandwich",
    name_ar: "ساندويتش سلات المدينة",
    desc_en: "Sandwich filled with a variety of city salads.",
    desc_ar: "ساندويتش محشو بمجموعة متنوعة من سلطات المدينة.",
    image: "sdsd",
    category_en: "wheat bread sandwich",
    category_ar: "ساندوتش عيش الحب",
    calories: 0,
    price: 25,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "0",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "grain bread/local bread",
      "assorted salads (likely: lettuce, tomatoes, cucumbers, onions, mayonnaise/tahini)",
    ],
    ingredients_ar: [
      "خبز أسمر/بلدي",
      "سلطات متنوعة (محتمل: خس, طماطم, خيار, بصل, مايونيز/طحينة)",
    ],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: 1,
    notes_en: "Served with potato chips and sauce.",
    notes_ar: "يقدم مع بطاطس شيبس وصوص.",
  },
  //pages from 13 to 18 40s
  // {
  //   id: "ARABIAN-RICE-CHICKEN",
  //   code: "ARABIAN-RICE-CHICKEN",
  //   name_en: "Arabian Rice & To'mah's Chicken",
  //   name_ar: "رز عربي ودجاج طعمة",
  //   desc_en: "Indulge in a plate of premium white rice with chicken marinated in To'mah's special blend of yogurt, saffron, and potatoes. This delicious dish is served with yogurt and spicy salad to give you an authentic Arabian dining experience rich in flavors.",
  //   desc_ar: "استمتع بطبق من الرز الأبيض الفاخر مع الدجاج المتبل بطريقة طعمة الخاصة باللبن والزعفران والبطاطس. يقدم هذا الطبق الشهي مع سلطة اللبن وسلطة حارة ليمنحك تجربة طعام عربية أصيلة وغنية بالنكهات.",
  //   image: "img11",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1788,
  //   price: 40,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "chicken",
  //     "yogurt",
  //     "saffron",
  //     "potatoes",
  //     "special spices",
  //     "yogurt",
  //     "chili peppers",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "دجاج",
  //     "لبن",
  //     "زعفران",
  //     "بطاطس",
  //     "بهارات خاصة",
  //     "لبن",
  //     "فلفل حار",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1-2",
  //   notes_en: "Authentic Arabian taste with To'mah's distinctive touch. A meal rich in delicious flavors and spices.",
  //   notes_ar: "طعم عربي أصيل مع لمسة طعمة المميزة. وجبة غنية بالنكهات والتوابل الشهية."
  // },
  // {
  //   id: "31",
  //   code: "AWSAL-CHICKEN",
  //   name_en: "Awsal Chicken",
  //   name_ar: "أوصال دجاج",
  //   desc_en: "Indulge in grilled chicken breast pieces served with creamy garlic sauce. A delicious and light meal rich in protein and delightful grilled flavors.",
  //   desc_ar: "استمتع بقطع صدور دجاج مشوية على السيخ وتقدم مع صوص الثوم الكريمي. وجبة شهية وخفيفة وغنية بالبروتين والنكهات المشوية اللذيذة.",
  //   image: "img17",
  //   category_en: "Grilled Te'ama",
  //   category_ar: "منقل طعمة",
  //   calories: 343,
  //   price: 55,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "chicken breasts",
  //     "spices",
  //     "garlic",
  //     "mayonnaise",
  //     "lemon",
  //     "vegetables for garnish"
  //   ],
  //   ingredients_ar: [
  //     "صدور دجاج",
  //     "بهارات",
  //     "ثوم",
  //     "مايونيز",
  //     "ليمون",
  //     "خضروات للتزيين"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of grilled chicken with creamy garlic sauce. A simple, delicious, and nutritious meal.",
  //   notes_ar: "طعم الدجاج المشوي مع صوص الثوم الكريمي. وجبة بسيطة ولذيذة ومغذية."
  // },
  // {
  //   id: "32",
  //   code: "BAKED-MANTU",
  //   name_en: "Baked Mantu",
  //   name_ar: "منتو فرنّي",
  //   desc_en: "Enjoy two pieces of fresh oven-baked Mantu, filled with fresh and carefully seasoned beef. A light and healthy dish with a distinctive flavor, perfect as a light meal or a delicious appetizer.",
  //   desc_ar: "استمتع بقطعتين من المنتو الطازج المخبوز في الفرن، محشو باللحم الطازج والمتبل بعناية. طبق خفيف وصحي بنكهة مميزة، مثالي كوجبة خفيفة أو مقبل شهي.",
  //   image: "img3",
  //   category_en: "pastry basket",
  //   category_ar: "سلة معجنات",
  //   calories: 222,
  //   price: 15,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "flour",
  //     "minced beef",
  //     "onion",
  //     "spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "لحم مفروم",
  //     "بصل",
  //     "بهارات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "Soft texture on the outside and delicious filling on the inside. A healthy and nutritious choice.",
  //   notes_ar: "قوام طري من الخارج وحشوة لذيذة من الداخل. خيار صحي ومغذي."
  // },
  // {
  //   id: "33",
  //   code: "BEEF-YAGHMASH",
  //   name_en: "Beef Yaghmash",
  //   name_ar: "يغمش لحم",
  //   desc_en: "Indulge in four pieces of delicious Yaghmash, filled with beef seasoned with a special and distinctive blend. A tasty and flavorful dish, perfect as a light meal or an appetizer that adds an authentic Eastern touch to your table.",
  //   desc_ar: "استمتع بأربع قطع من اليغمش اللذيذ، محشوة باللحم المتبل بخلطة خاصة ومميزة. طبق شهي وغني بالنكهات، مثالي كوجبة خفيفة أو مقبل يضيف لمسة شرقية أصيلة إلى مائدتك.",
  //   image: "img4",
  //   category_en: "pastry basket",
  //   category_ar: "سلة معجنات",
  //   calories: 202,
  //   price: 12,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "flour",
  //     "minced beef",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "لحم مفروم",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "A flavor rich in Eastern spices and a delicious aroma that captivates the senses. Served hot with sauce (optional).",
  //   notes_ar: "نكهة غنية بالتوابل الشرقية ورائحة شهية تأسر الحواس. يقدم ساخنًا مع صوص (حسب الرغبة)."
  // },
  {
    id: "34",
    code: "BEEF-JOINTS",
    name_en: "Beef Joints",
    name_ar: "أوصال لحم",
    desc_en:
      "Indulge in grilled beef joints served with rich tahini sauce. A delicious meal rich in protein and authentic grilled flavors.",
    desc_ar:
      "استمتع بقطع أوصال لحم مشوية على السيخ وتقدم مع صوص الطحينة الغني. وجبة شهية وغنية بالبروتين والنكهات المشوية الأصيلة.",
    image: img35,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 0,
    price: 75,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "beef joints",
      "spices",
      "tahini",
      "lemon",
      "vegetables for garnish",
    ],
    ingredients_ar: ["قطع لحم", "بهارات", "طحينة", "ليمون", "خضروات للتزيين"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of grilled meat with the distinctive tahini sauce. A simple, delicious, and nutritious meal.",
    notes_ar:
      "طعم اللحم المشوي مع صوص الطحينة المميز. وجبة بسيطة ولذيذة ومغذية.",
  },
  // {
  //   id: "35",
  //   code: "BEEF-MUQALQAL",
  //   name_en: "Beef Muqalqal",
  //   name_ar: "مقلقل لحم",
  //   desc_en: "Indulge in beef muqalqal pieces with the special blend, served in the Ahl Awl style. A delicious meal rich in traditional and distinctive flavors.",
  //   desc_ar: "استمتع بقطع لحم مقلقل بالخلطة وتقدم بطريقة أهل أول. وجبة شهية وغنية بالنكهات التقليدية والمميزة.",
  //   image: "img20",
  //   category_en: "Breakfast/Chef's Breakfast",
  //   category_ar: "فطور/فطور الطباخة",
  //   calories: 607,
  //   price: 40,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "beef pieces",
  //     "onion",
  //     "tomatoes",
  //     "peppers",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "قطع لحم",
  //     "بصل",
  //     "طماطم",
  //     "فلفل",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of tender beef with the special blend in the Ahl Awl style. A popular, delicious, and nutritious meal.",
  //   notes_ar: "طعم اللحم الطري مع الخلطة المميزة على طريقة أهل أول. وجبة شعبية ولذيذة ومغذية."
  // },
  // {
  //   id: "36",
  //   code: "BUKHARI-JAWAZAT",
  //   name_en: "Bukhari Rice Jawazat",
  //   name_ar: "رز بخاري جوازات",
  //   desc_en: "Indulge in a plate of Bukhari rice prepared in the Jawazat Ahl Awal style, with a piece of slow-cooked meat seasoned with a special blend of spices. This delicious dish is garnished with a mixture of raisins, balila, and almonds, and served with dakos and a refreshing green salad for an authentic dining experience and an unforgettable taste.",
  //   desc_ar: "استمتع بطبق من الرز البخاري المعد على طريقة جوازات أهل أول، مع قطعة من اللحم المطهو ببطء والمتبل بخلطة بهارات خاصة. يزين هذا الطبق الشهي بمزيج من الزبيب والبليلة واللوز، ويقدم مع سلطة الدقس وسلطة خضراء منعشة لتجربة طعام أصيلة ومذاق لا يُنسى.",
  //   image: "img7",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1755,
  //   price: 97,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "Bukhari rice",
  //     "meat",
  //     "raisins",
  //     "balila",
  //     "almonds",
  //     "special spices",
  //     "dakos",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز بخاري",
  //     "لحم",
  //     "زبيب",
  //     "بليلة",
  //     "لوز",
  //     "بهارات خاصة",
  //     "دقس",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1-2",
  //   notes_en: "An authentic taste from the heart of heritage, and a delicious aroma that takes you on a journey through time. A luxurious and nutritious meal for special and family occasions.",
  //   notes_ar: "طعم أصيل من قلب التراث، ورائحة شهية تأخذك في رحلة عبر الزمن. وجبة فاخرة ومغذية للمناسبات الخاصة والعائلية."
  // },
  // {
  //   id: "37",
  //   code: "BUKHARI-SIT-ALBEIT",
  //   name_en: "Bukhari Rice Sit Al-Beit",
  //   name_ar: "رز بخاري ست البيت",
  //   desc_en: "Indulge in a plate of Bukhari rice prepared with chicken in the Sit Al-Beit style, a distinctive recipe from Jawazat Ahl Awal. This dish features a unique blend of spices and a delicious mix of raisins, balila, and almonds. Served with dakos and a refreshing green salad for an authentic homemade dining experience and an unforgettable taste.",
  //   desc_ar: "استمتع بطبق من الرز البخاري المعد بالدجاج على طريقة ست البيت، وهي وصفة مميزة من جوازات أهل أول. يتميز هذا الطبق بخلطة بهارات فريدة ومزيج شهي من الزبيب والبليلة واللوز. يقدم مع سلطة الدقس وسلطة خضراء منعشة لتجربة طعام منزلية أصيلة ومذاق لا يُنسى.",
  //   image: "img8",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 146,
  //   price: 38,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "Bukhari rice",
  //     "chicken",
  //     "raisins",
  //     "balila",
  //     "almonds",
  //     "special spices",
  //     "dakos",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز بخاري",
  //     "دجاج",
  //     "زبيب",
  //     "بليلة",
  //     "لوز",
  //     "بهارات خاصة",
  //     "دقس",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The authentic taste of home and the distinctive touch of Sit Al-Beit in every bite. A warm and flavorful meal rich in family tastes.",
  //   notes_ar: "طعم البيوت الأصيل ولمسة ست البيت المميزة في كل لقمة. وجبة دافئة وغنية بالنكهات العائلية."
  // },
  {
    id: "38",
    code: "CHICKEN-KEBAB",
    name_en: "Grilled Chicken Kebab",
    name_ar: "كباب دجاج",
    desc_en:
      "Indulge in special chicken kebab grilled over charcoal, served with fresh green salad and rich tahini sauce. A delicious and light meal rich in protein and authentic grilled flavors.",
    desc_ar:
      "استمتع بكباب الدجاج المميز المشوي على الفحم، ويقدم مع السلطة الخضراء الطازجة وصوص الطحينة الغني. وجبة شهية وخفيفة وغنية بالبروتين والنكهات المشوية الأصيلة.",
    image: img37,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 343,
    price: 73,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "minced chicken",
      "onion",
      "special spices",
      "green salad",
      "tahini",
      "lemon",
    ],
    ingredients_ar: [
      "دجاج مفروم",
      "بصل",
      "بهارات خاصة",
      "سلطة خضراء",
      "طحينة",
      "ليمون",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of grilled kebab with the distinctive flavor of spices and fresh salad. A delicious and nutritious meal suitable for all times.",
    notes_ar:
      "طعم الكباب المشوي مع نكهة البهارات المميزة والسلطة الطازجة. وجبة شهية ومغذية ومناسبة لكل الأوقات.",
  },
  // {
  //   id: "39",
  //   code: "CHICKEN-MUQALQAL",
  //   name_en: "Chicken Muqalqal",
  //   name_ar: "مقلقل الدجاج",
  //   desc_en: "Indulge in chicken breast sautéed with fresh vegetables and special spices. A delicious and light meal rich in distinctive flavors.",
  //   desc_ar: "استمتع بقطع صدور دجاج مشوحة بالخضار الطازجة والبهارات الخاصة. وجبة شهية وخفيفة وغنية بالنكهات المميزة.",
  //   image: "img21",
  //   category_en: "Breakfast/Chef's Breakfast",
  //   category_ar: "فطور/فطور الطباخة",
  //   calories: 479,
  //   price: 30,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "chicken breasts",
  //     "onion",
  //     "tomatoes",
  //     "peppers",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "صدور دجاج",
  //     "بصل",
  //     "طماطم",
  //     "فلفل",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of tender chicken with sautéed vegetables and aromatic spices. A quick, delicious, and nutritious meal.",
  //   notes_ar: "طعم الدجاج الطري مع الخضار المشوحة والبهارات العطرية. وجبة سريعة ولذيذة ومغذية."
  // },
  // {
  //   id: "40",
  //   code: "DRIED-MOLOKHIA",
  //   name_en: "Dried Molokhia",
  //   name_ar: "ملوخية ناشفة",
  //   desc_en: "Choose from dried molokhia leaves cooked in the Ahl Awl style, with pieces of beef or roasted chicken, and served with grain bread and Madini rice. A delicious meal rich in the traditional and distinctive flavors of the city's locals.",
  //   desc_ar: "اختار من أوراق الملوخية الناشفة المطبوخة على طريقة أهل أول، مع قطع اللحم أو الدجاج المحمر، وتقدم بخبز الحب والرز المديني. وجبة شهية وغنية بالنكهات التقليدية والمميزة لأهل المدينة.",
  //   image: "img27",
  //   category_en: "Ta'meh cooking/casseroles",
  //   category_ar: "طبيخ طعمة/الإيدامات",
  //   calories: 329,
  //   price: 20,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "medium",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "dried molokhia",
  //     "beef or chicken",
  //     "onion",
  //     "garlic",
  //     "special spices",
  //     "grain bread",
  //     "Madini rice"
  //   ],
  //   ingredients_ar: [
  //     "ملوخية ناشفة",
  //     "لحم أو دجاج",
  //     "بصل",
  //     "ثوم",
  //     "بهارات خاصة",
  //     "خبز حب",
  //     "رز مديني"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of dried molokhia in the Ahl Awl style with tender beef or chicken, rice, and fresh grain bread. A warm and rich meal with authentic flavors.",
  //   notes_ar: "طعم الملوخية الناشفة على طريقة أهل أول مع اللحم أو الدجاج الطري والرز وخبز الحب الطازج. وجبة دافئة وغنية بالنكهات الأصيلة."
  // },
  // {
  //   id: "41",
  //   code: "GAMAH-RICE",
  //   name_en: "Gama'h Rice",
  //   name_ar: "رز الجمعه",
  //   desc_en: "Indulge in a plate of rice cooked with meat or chicken, chickpeas, and Linda's special ghee blend with an authentic ghee flavor. This delicious dish is served with sliced carrots, tahini sauce with cucumber, and pickled ahwaz carrots to give you a warm family meal rich in diverse flavors.",
  //   desc_ar: "استمتع بطبق من الرز المطبوخ باللحم أو الدجاج مع الحمص وخلطة ليندا الخاصة بطعم السمن الأصيل. يقدم هذا الطبق الشهي مع قطع من الجزر الشرائح وصوص الطحينة بالخيار والمخلل الأهواز ليمنحك وجبة عائلية دافئة وغنية بالنكهات المتنوعة.",
  //   image: "img9",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 138,
  //   price: 97,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "meat or chicken",
  //     "chickpeas",
  //     "ghee",
  //     "carrots",
  //     "tahini",
  //     "cucumber",
  //     "pickles",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "لحم أو دجاج",
  //     "حمص",
  //     "سمن",
  //     "جزر",
  //     "طحينة",
  //     "خيار",
  //     "مخلل",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "2-3",
  //   notes_en: "The taste of togetherness and family gatherings in one dish. A warm and rich meal that combines authentic flavors with refreshing appetizers.",
  //   notes_ar: "طعم الجماعة ولمة العيلة في طبق واحد. وجبة دافئة وغنية تجمع بين النكهات الأصيلة والمقبلات المنعشة."
  // },
  // {
  //   id: "42",
  //   code: "GREEN-MOLOKHIA",
  //   name_en: "Green Molokhia",
  //   name_ar: "ملوخية خضراء",
  //   desc_en: "Choose from green molokhia leaves cooked in the Ahl Awl style, with pieces of beef or roasted chicken, and served with grain bread and Madini rice. A delicious meal rich in the traditional and distinctive flavors of the city's locals.",
  //   desc_ar: "اختار من أوراق الملوخية الخضرا المطبوخة على طريقة أهل أول، مع قطع اللحم أو الدجاج المحمر، وتقدم بخبز الحب والرز المديني. وجبة شهية وغنية بالنكهات التقليدية والمميزة لأهل المدينة.",
  //   image: "img26",
  //   category_en: "Ta'meh cooking/casseroles",
  //   category_ar: "طبيخ طعمة/الإيدامات",
  //   calories: 351,
  //   price: 20,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "medium",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "green molokhia",
  //     "beef or chicken",
  //     "onion",
  //     "garlic",
  //     "special spices",
  //     "grain bread",
  //     "Madini rice"
  //   ],
  //   ingredients_ar: [
  //     "ملوخية خضرا",
  //     "لحم أو دجاج",
  //     "بصل",
  //     "ثوم",
  //     "بهارات خاصة",
  //     "خبز حب",
  //     "رز مديني"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of green molokhia in the Ahl Awl style with tender beef or chicken, rice, and fresh grain bread. A warm and rich meal with authentic flavors.",
  //   notes_ar: "طعم الملوخية الخضرا على طريقة أهل أول مع اللحم أو الدجاج الطري والرز وخبز الحب الطازج. وجبة دافئة وغنية بالنكهات الأصيلة."
  // },
  // {
  //   id: "43",
  //   code: "GRILLED-CHICKEN",
  //   name_en: "Grilled Chicken",
  //   name_ar: "دجاج شواية",
  //   desc_en: "Indulge in a delicious meal consisting of Bukhari rice prepared in a special way and a piece of grilled chicken seasoned with TO'MAH's signature spices. This dish is served with a variety of side dishes for a complete and tasty dining experience.",
  //   desc_ar: "استمتع بوجبة شهية تتكون من رز بخاري معد بطريقة مميزة وقطعة من الدجاج المشوي والمتبل ببهارات طعمة الخاصة. يقدم هذا الطبق مع أطباق جانبية متنوعة لتجربة طعام متكاملة ولذيذة.",
  //   image: "img10",
  //   category_en: "Grilled Te'ama",
  //   category_ar: "منقل طعمة",
  //   calories: 465,
  //   price: 38,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "Bukhari rice",
  //     "chicken",
  //     "special spices",
  //     "side dishes (as available)"
  //   ],
  //   ingredients_ar: [
  //     "أرز بخاري",
  //     "دجاج",
  //     "بهارات خاصة",
  //     "أطباق جانبية (حسب المتوفر)"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The distinctive flavor of the grilled chicken's special spices with the delicious Bukhari rice. A complete and nutritious meal suitable for all times.",
  //   notes_ar: "طعم البهارات المميزة للدجاج المشوي مع الرز البخاري الشهي. وجبة متكاملة ومغذية تناسب جميع الأوقات."
  // },
  // {
  //   id: "44",
  //   code: "HEAD-MEAT",
  //   name_en: "Head Meat",
  //   name_ar: "لحمة راس",
  //   desc_en: "Indulge in boneless pieces of mutton head beef baked in the oven and served with grain bread and tahini. A delicious meal rich in traditional and distinctive flavors.",
  //   desc_ar: "استمتع بقطع لحم مخلية من رأس الخروف المشوي بالفرن وتقدم مع خبز الحب والطحينة. وجبة شهية وغنية بالنكهات التقليدية والمميزة.",
  //   image: "img22",
  //   category_en: "Breakfast/Chef's Breakfast",
  //   category_ar: "فطور/فطور الطباخة",
  //   calories: 297,
  //   price: 30,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "mutton head beef",
  //     "spices",
  //     "grain bread",
  //     "tahini",
  //     "lemon",
  //     "vegetables for garnish"
  //   ],
  //   ingredients_ar: [
  //     "لحم رأس خروف",
  //     "بهارات",
  //     "خبز حب",
  //     "طحينة",
  //     "ليمون",
  //     "خضروات للتزيين"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of grilled meat with fresh grain bread and rich tahini sauce. A popular, delicious, and nutritious meal.",
  //   notes_ar: "طعم اللحم المشوي مع خبز الحب الطازج وصوص الطحينة الغني. وجبة شعبية ولذيذة ومغذية."
  // },
  {
    id: "45",
    code: "HIJAZI-KEBAB",
    name_en: "Hijazi Kebab",
    name_ar: "كباب حجازي",
    desc_en:
      "Indulge in traditional Hijazi kebab grilled over charcoal, served with fresh green salad and rich tahini sauce. A delicious meal rich in the traditional flavors that distinguish Hijazi cuisine.",
    desc_ar:
      "استمتع بالكباب الحجازي الأصيل المشوي على الفحم، ويقدم مع السلطة الخضراء الطازجة وصوص الطحينة الغني. وجبة شهية وغنية بالنكهات التقليدية التي تميز المطبخ الحجازي.",
    image: img36,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 343,
    price: 73,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "minced meat",
      "onion",
      "Hijazi spices",
      "green salad",
      "tahini",
      "lemon",
    ],
    ingredients_ar: [
      "لحم مفروم",
      "بصل",
      "بهارات حجازية",
      "سلطة خضراء",
      "طحينة",
      "ليمون",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The authentic taste of Hijazi kebab with the distinctive flavor of spices and fresh salad. A delicious and nutritious meal suitable for all times.",
    notes_ar:
      "طعم الكباب الحجازي الأصيل مع نكهة البهارات المميزة والسلطة الطازجة. وجبة شهية ومغذية ومناسبة لكل الأوقات.",
  },
  // {
  //   id: "46",
  //   code: "LAHM-BEEF",
  //   name_en: "Lahmacun",
  //   name_ar: "عيش باللحم",
  //   desc_en: "Enjoy a piece of thin dough filled with fresh minced beef seasoned with a special and distinctive tahini mix. This dish is served soft and hot to give you an unforgettable dining experience.",
  //   desc_ar: "استمتع بقطعة من العجين الرقيق المحشو باللحم المفروم الطازج والمتبل بخلطة طحينة خاصة ومميزة. يقدم هذا الطبق ساخناً وطرياً ليمنحك تجربة طعام لا تُنسى.",
  //   image: "img19",
  //   category_en: "pastry basket",
  //   category_ar: "سلة معجنات",
  //   calories: 310,
  //   price: 20,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "flour",
  //     "minced beef",
  //     "tahini",
  //     "onion",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "لحم مفروم",
  //     "طحينة",
  //     "بصل",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "A unique blend of meat and tahini that melts in your mouth. Perfect for a quick and delicious meal.",
  //   notes_ar: "مزيج فريد من اللحم والطحينة يذوب في الفم. مثالي لوجبة سريعة ولذيذة."
  // },
  // {
  //   id: "47",
  //   code: "KABULI-CHICKEN-SIT",
  //   name_en: "Kabuli Rice Sit Al-Beit",
  //   name_ar: "الرز الكابلي ل ست البيت",
  //   desc_en: "Indulge in a plate of chicken rice flavored with orange zest and saffron, served with a special sour potato kashneh. This delicious dish is accompanied by yogurt salad and spicy salad to give you a unique homemade dining experience rich in diverse flavors.",
  //   desc_ar: "استمتع بطبق من رز الدجاج المنكه بقشر البرتقال والزعفران مع كشنة البطاطس الحامض الخاصة. يقدم هذا الطبق الشهي مع سلطة اللبن وسلطة حارة ليمنحك تجربة طعام منزلية مميزة وغنية بالنكهات المتنوعة.",
  //   image: "img6",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 149,
  //   price: 38,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "chicken",
  //     "orange zest",
  //     "saffron",
  //     "potatoes",
  //     "special spices",
  //     "yogurt",
  //     "chili peppers",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "دجاج",
  //     "قشر برتقال",
  //     "زعفران",
  //     "بطاطس",
  //     "بهارات خاصة",
  //     "لبن",
  //     "فلفل حار",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "A unique blend of sweet, sour, and spicy flavors with an authentic homemade touch. An unforgettable home-style dining experience and a delicious taste favored by everyone.",
  //   notes_ar: "مزيج فريد من النكهات الحلوة والحامضة والحارة بلمسة ست البيت الأصيلة. تجربة طعام منزلية لا تُنسى ومذاق شهي يفضله الجميع."
  // },
  // {
  //   id: "48",
  //   code: "KABULI-MADINI",
  //   name_en: "Kabuli Madini Rice",
  //   name_ar: "رز المدينة الكابلي المشهور",
  //   desc_en: "Indulge in a plate of meat rice flavored with orange zest and saffron, served with a special sour potato kashneh. This famous dish is accompanied by yogurt salad and spicy salad to give you a unique dining experience rich in diverse flavors.",
  //   desc_ar: "استمتع بطبق من الرز باللحم المنكه بقشر البرتقال والزعفران مع كشنة البطاطس الحامض الخاصة. يقدم هذا الطبق الشهير مع سلطة اللبن وسلطة حارة ليمنحك تجربة طعام فريدة وغنية بالنكهات المتنوعة.",
  //   image: "img5",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1876,
  //   price: 97,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "meat",
  //     "orange zest",
  //     "saffron",
  //     "potatoes",
  //     "special spices",
  //     "yogurt",
  //     "chili peppers",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "لحم",
  //     "قشر برتقال",
  //     "زعفران",
  //     "بطاطس",
  //     "بهارات خاصة",
  //     "لبن",
  //     "فلفل حار",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1-2",
  //   notes_en: "A unique blend of sweet, sour, and spicy flavors in one dish. An unforgettable dining experience and a famous taste favored by many.",
  //   notes_ar: "مزيج فريد من النكهات الحلوة والحامضة والحارة في طبق واحد. تجربة طعام لا تُنسى ومذاق شهير يفضله الكثيرون."
  // },
  {
    id: "MABSHOURBEEF",
    code: "MABSHOUR-BEEF",
    name_en: 'Mabshoor "Minced" Beef',
    name_ar: "مبشور اللحم",
    desc_en:
      "Indulge in minced beef grilled on skewers with a selection of fresh grilled vegetables, served with a refreshing salad. A delicious meal rich in grilled flavors, perfect for meat and vegetable lovers.",
    desc_ar:
      "استمتع بلحم مفروم مشوي على السيخ مع تشكيلة من الخضار المشوية الطازجة، ويقدم مع سلطة منعشة. وجبة شهية وغنية بالنكهات المشوية، مثالية لمحبي اللحوم والخضروات.",
    image: img33,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 0,
    price: 73,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "minced beef",
      "onion",
      "spices",
      "grilled vegetables (tomatoes, peppers, ...)",
      "salad",
    ],
    ingredients_ar: [
      "لحم مفروم",
      "بصل",
      "بهارات",
      "خضار مشوية (طماطم, فلفل, ...)",
      "سلطة",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of grilled meat with the flavor of spices and fresh vegetables. A healthy, delicious, and nutritious meal.",
    notes_ar:
      "طعم اللحم المشوي مع نكهة البهارات والخضار الطازجة. وجبة صحية ولذيذة ومغذية.",
  },
  {
    id: "50",
    code: "MABSHOUR-CHICKEN",
    name_en: "Mabshoor Minced Chicken",
    name_ar: "مبشور دجاج",
    desc_en:
      "Indulge in minced chicken pieces grilled on skewers and served with a selection of fresh grilled vegetables and a refreshing salad. A light and delicious meal rich in protein and grilled flavors.",
    desc_ar:
      "استمتع بقطع دجاج مفروم مشوية على السيخ وتقدم مع تشكيلة من الخضار المشوية الطازجة وسلطة منعشة. وجبة خفيفة ولذيذة وغنية بالبروتين والنكهات المشوية.",
    image: img34,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 0,
    price: 75,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "minced chicken",
      "onion",
      "spices",
      "grilled vegetables (tomatoes, peppers, ...)",
      "salad",
    ],
    ingredients_ar: [
      "دجاج مفروم",
      "بصل",
      "بهارات",
      "خضار مشوية (طماطم, فلفل, ...)",
      "سلطة",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of grilled chicken with the flavor of spices and fresh vegetables. A healthy, light, and nutritious meal.",
    notes_ar:
      "طعم الدجاج المشوي مع نكهة البهارات والخضار الطازجة. وجبة صحية وخفيفة ومغذية.",
  },
  // {
  //   id: "MADINI-COLLAGEN",
  //   code: "MADINI-COLLAGEN",
  //   name_en: "Madini Collagen",
  //   name_ar: "مقادم (كولاجين المدينة)",
  //   desc_en: "Indulge in two pieces of boiled lamb feet, served with grain bread and a lemon-garlic mix. A delicious meal rich in collagen and the traditional and distinctive flavors of the city's locals.",
  //   desc_ar: "استمتع بقطعتين من كوارع الغنم المسلوقة، وتقدم مع خبز الحب وخلطة الليمون بالثوم. وجبة شهية وغنية بالكولاجين والنكهات التقليدية والمميزة لأهل المدينة.",
  //   image: "img28",
  //   category_en: "Ta'meh cooking/casseroles",
  //   category_ar: "طبيخ طعمة/الإيدامات",
  //   calories: 0,
  //   price: 27,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "طويل",
  //   cookTime_en: "long",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "lamb feet",
  //     "garlic",
  //     "lemon",
  //     "spices",
  //     "grain bread"
  //   ],
  //   ingredients_ar: [
  //     "كوارع غنم",
  //     "ثوم",
  //     "ليمون",
  //     "بهارات",
  //     "خبز حب"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of collagen-rich trotters with refreshing lemon and garlic and fresh grain bread. A warm and nutritious meal suitable for lovers of popular dishes.",
  //   notes_ar: "طعم الكوارع الغنية بالكولاجين مع الليمون والثوم المنعش وخبز الحب الطازج. وجبة دافئة ومغذية ومناسبة لمحبي الأكلات الشعبية."
  // },
  // {
  //   id: "MADINI-RICE-BEEF",
  //   code: "MADINI-RICE-BEEF",
  //   name_en: "Madini Rice with Beef",
  //   name_ar: "رز مديني باللحم",
  //   desc_en: "Indulge in a plate of premium white rice with a piece of roasted lamb flavored with TO'MAH's special blend of lamb ghee, saffron, and barberry. This delicious dish is served with dakos and yogurt salad to give you a complete and flavorful authentic meal.",
  //   desc_ar: "استمتع بطبق من الأرز الأبيض الفاخر مع قطعة من لحم الضأن المحمر والمنكه بخلطة طعمة الخاصة من السمن الغنمي والزعفران والزرشك الأحمر. يقدم هذا الطبق الشهي مع سلطة الدقس وسلطة اللبن ليمنحك وجبة متكاملة وغنية بالنكهات الأصيلة.",
  //   image: "img1",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1720,
  //   price: 97,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "lamb",
  //     "lamb ghee",
  //     "saffron",
  //     "barberry",
  //     "special spices",
  //     "dakos",
  //     "yogurt",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "لحم ضأن",
  //     "سمن غنمي",
  //     "زعفران",
  //     "زرشك",
  //     "بهارات خاصة",
  //     "دقس",
  //     "لبن",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1-2",
  //   notes_en: "A flavor rich in Eastern authenticity and a delicious aroma that fills the place. A luxurious and nutritious meal.",
  //   notes_ar: "طعم غني بالأصالة الشرقية ورائحة شهية تملأ المكان. وجبة فاخرة ومغذية."
  // },
  // {
  //   id: "MADINI-RICE-CHICKEN",
  //   code: "MADINI-RICE-CHICKEN",
  //   name_en: "Madini Rice with Chicken",
  //   name_ar: "رز مديني بالدجاج",
  //   desc_en: "Indulge in a plate of premium white rice with a piece of roasted chicken flavored with TO'MAH's special blend of lamb ghee, saffron, and barberry. This delicious dish is served with dakos and yogurt salad to give you a complete and flavorful authentic meal.",
  //   desc_ar: "استمتع بطبق من الأرز الأبيض الفاخر مع قطعة من الدجاج المحمر والمنكه بخلطة طعمة الخاصة من السمن الغنمي والزعفران والزرشك الأحمر. يقدم هذا الطبق الشهي مع سلطة الدقس وسلطة اللبن ليمنحك وجبة متكاملة وغنية بالنكهات الأصيلة.",
  //   image: "img2",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1310,
  //   price: 38,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "chicken",
  //     "lamb ghee",
  //     "saffron",
  //     "barberry",
  //     "special spices",
  //     "dakos",
  //     "yogurt",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "دجاج",
  //     "سمن غنمي",
  //     "زعفران",
  //     "زرشك",
  //     "بهارات خاصة",
  //     "دقس",
  //     "لبن",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "A flavor rich in authentic Eastern taste and a delicious aroma that fills the atmosphere. A luxurious and nutritious meal suitable for all times.",
  //   notes_ar: "طعم غني بالنكهة الشرقية الأصيلة ورائحة شهية تملأ الأجواء. وجبة فاخرة ومغذية تناسب جميع الأوقات."
  // },
  // {
  //   id: "MADINI-SALAT",
  //   code: "MADINI-SALAT",
  //   name_en: "Madini Salat",
  //   name_ar: "سلات أهل المدينة",
  //   desc_en: "Indulge in tender beef chunks slow-cooked with onion and garlic, served with grain bread and Madini rice. A delicious meal rich in the traditional and distinctive flavors of the city's locals.",
  //   desc_ar: "استمتع بقطع لحم طرية مطبوخة بالبصل والثوم على نار هادئة، وتقدم مع خبز الحب والرز المديني. وجبة شهية وغنية بالنكهات التقليدية والمميزة لأهل المدينة.",
  //   image: "img25",
  //   category_en: "Ta'mat Al-Madinah dishes",
  //   category_ar: "أطباق  طعمة  المدينة",
  //   calories: 0,
  //   price: 45,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "long",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "beef chunks",
  //     "onion",
  //     "garlic",
  //     "special spices",
  //     "grain bread",
  //     "Madini rice"
  //   ],
  //   ingredients_ar: [
  //     "قطع لحم",
  //     "بصل",
  //     "ثوم",
  //     "بهارات خاصة",
  //     "خبز حب",
  //     "رز مديني"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of tender, slow-cooked meat with Madini rice and fresh grain bread. A warm and rich meal with authentic flavors.",
  //   notes_ar: "طعم اللحم الطري المطهو ببطء مع الرز المديني وخبز الحب الطازج. وجبة دافئة وغنية بالنكهات الأصيلة."
  // },
  {
    id: "MANTUFUTO",
    code: "MANTU-FUTO",
    name_en: "Mantu Futo",
    name_ar: "منتو فتو",
    desc_en:
      "Indulge in four pieces of delicious Mantu, filled with a savory stuffing and topped with a sprinkle of aromatic cumin and spicy black pepper. An authentic traditional dish with a distinctive flavor that takes you on a journey to the world of Eastern tastes.",
    desc_ar:
      "استمتع بأربع قطع من المنتو الشهي، محشوة بحشوة لذيذة ومغطاة برشة من الكمون العطري والفلفل الأسود الحار. طبق تقليدي أصيل بنكهة مميزة تأخذك في رحلة إلى عالم من المذاقات الشرقية.",
    image: img29,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 268,
    price: 15,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "flour",
      "minced meat",
      "onion",
      "spices",
      "cumin",
      "black pepper",
    ],
    ingredients_ar: ["دقيق", "لحم مفروم", "بصل", "بهارات", "كمون", "فلفل أسود"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "A flavor rich in spices and an irresistible aroma. Served hot with sauce (optional).",
    notes_ar:
      "طعم غني بالتوابل ورائحة لا تقاوم. يقدم ساخنًا مع صوص (حسب الرغبة).",
  },
  // {
  //   id: "OKRA-MADINI",
  //   code: "OKRA-MADINI",
  //   name_en: "Okra",
  //   name_ar: "مختوم بامية",
  //   desc_en: "Indulge in Madini okra cooked with tender beef chunks, served with grain bread and Madini rice. A delicious meal rich in the traditional and distinctive flavors of the city's locals.",
  //   desc_ar: "استمتع ببامية مدينية مطبوخة بقطع اللحم الطرية، وتقدم بخبز الحب والرز المديني. وجبة شهية وغنية بالنكهات التقليدية والمميزة لأهل المدينة.",
  //   image: "img24",
  //   category_en: "Ta'meh cooking/casseroles",
  //   category_ar: "طبيخ طعمة/الإيدامات",
  //   calories: 243,
  //   price: 20,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "long",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "okra",
  //     "beef",
  //     "onion",
  //     "tomatoes",
  //     "special spices",
  //     "grain bread",
  //     "Madini rice"
  //   ],
  //   ingredients_ar: [
  //     "بامية",
  //     "لحم",
  //     "بصل",
  //     "طماطم",
  //     "بهارات خاصة",
  //     "خبز حب",
  //     "رز مديني"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of okra cooked in the Madini style with tender beef, rice, and fresh grain bread. A warm and rich meal with authentic flavors.",
  //   notes_ar: "طعم البامية المطبوخة على الطريقة المدينية مع اللحم الطري والرز وخبز الحب الطازج. وجبة دافئة وغنية بالنكهات الأصيلة."
  // },
  // {
  //   id: "POTATO-KEBAB-TRAY",
  //   code: "POTATO-KEBAB-TRAY",
  //   name_en: "Potato Kebab Tray",
  //   name_ar: "صينية الكباب بالبطاطس",
  //   desc_en: "Indulge in a special tray of potatoes and kebab grilled in the oven, served with delicious Madini rice and spicy dakos sauce. A delicious family meal rich in diverse flavors.",
  //   desc_ar: "استمتع بصينية مخصوصة من البطاطس والكباب المشوي بالفرن، وتقدم مع الرز المديني الشهي وصوص الدقس الحار. وجبة عائلية شهية وغنية بالنكهات المتنوعة.",
  //   image: "img23",
  //   category_en: "Ta'meh cooking/casseroles",
  //   category_ar: "طبيخ طعمة/الإيدامات",
  //   calories: 289,
  //   price: 27,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "medium",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "kebab",
  //     "potatoes",
  //     "onion",
  //     "tomatoes",
  //     "peppers",
  //     "special spices",
  //     "Madini rice",
  //     "dakos"
  //   ],
  //   ingredients_ar: [
  //     "كباب",
  //     "بطاطس",
  //     "بصل",
  //     "طماطم",
  //     "فلفل",
  //     "بهارات خاصة",
  //     "رز مديني",
  //     "دقس"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "2-3",
  //   notes_en: "The taste of grilled kebab with potatoes, vegetables, and delicious Madini rice. A complete, delicious, and nutritious meal that combines all the favorites.",
  //   notes_ar: "طعم الكباب المشوي مع البطاطس والخضار والرز المديني الشهي. وجبة متكاملة ولذيذة ومغذية تجمع بين كل الأصناف اللي نحبها."
  // },
  // {
  //   id: "PUFFS-BEEF-2",
  //   code: "PUFFS-BEEF-2",
  //   name_en: "Beef Puffs",
  //   name_ar: "بف باللحم",
  //   desc_en: "Two delicious pieces of puffs filled with fresh and carefully seasoned beef, encased in a golden, crispy, and flaky pastry. A delightful light meal or a distinctive appetizer that satisfies all tastes.",
  //   desc_ar: "استمتع بقطعتين شهيتين من البف المحشو باللحم الطازج والمتبل بعناية، داخل عجينة ذهبية هشة ومقرمشة. وجبة خفيفة لذيذة أو مقبل مميز يرضي جميع الأذواق.",
  //   image: "img18",
  //   category_en: "pastry basket",
  //   category_ar: "سلة معجنات",
  //   calories: 322,
  //   price: 9,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "puff pastry",
  //     "minced beef",
  //     "spices"
  //   ],
  //   ingredients_ar: [
  //     "عجينة بف",
  //     "لحم مفروم",
  //     "بهارات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "2",
  //   notes_en: "An irresistible taste and enjoyable crispiness in every bite. Served hot with a special sauce (optional).",
  //   notes_ar: "طعم لا يقاوم وقرمشة ممتعة في كل قضمة. يقدم ساخنًا مع صوص مميز (حسب الرغبة)."
  // },
  {
    id: "QADIQUDAH",
    code: "QADI-QUDAH",
    name_en: "Qadi al Qudah",
    name_ar: "قاضي قاضي",
    desc_en:
      "Enjoy the most famous and popular meatballs in the dishes of the city's locals! These delicious balls are prepared with a special and distinctive recipe to give you an unforgettable taste. An irresistible dish favored by everyone.",
    desc_ar:
      "استمتع بكرات اللحم الأشهر والأكثر شعبية في أطباق أهل المدينة! هذه الكرات اللذيذة محضرة بوصفة خاصة ومميزة لتمنحك طعماً لا يُنسى. طبق لا يقاوم يفضله الجميع.",
    image: img31,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 271,
    price: 15,
    rating: 0,
    available: true,
    trendy: true,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: ["minced meat", "onion", "special spices", "herbs"],
    ingredients_ar: ["لحم مفروم", "بصل", "بهارات خاصة", "أعشاب"],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "Authentic taste and wide popularity make it the perfect choice every time. Served hot with a special sauce.",
    notes_ar:
      "طعم أصيل وشهرة واسعة تجعل منه الاختيار الأمثل في كل مرة. يقدم ساخناً مع صوص مميز.",
  },
  // {
  //   id: "SALEEQ-BEEF",
  //   code: "SALEEQ-BEEF",
  //   name_en: "Beef Saleeq",
  //   name_ar: "سليق باللحم",
  //   desc_en: "Indulge in a plate of milk-boiled rice prepared with special flavors, served with a piece of meat roasted in sheep ghee and spicy dakos sauce. This delicious dish is accompanied by dakos and spicy salad to give you a traditional dining experience rich in flavors.",
  //   desc_ar: "استمتع بطبق من الرز المسلوق بالحليب والمحضر بنكهة خاصة، ويقدم مع قطعة من اللحم المحمر بالسمن الغنمي وصوص الدقس الحار. يقدم هذا الطبق الشهي مع الدقس وسلطة حارة ليمنحك تجربة طعام تقليدية غنية بالنكهات.",
  //   image: "img11",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1622,
  //   price: 97,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "milk",
  //     "meat",
  //     "sheep ghee",
  //     "special spices",
  //     "dakos",
  //     "chili peppers",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "حليب",
  //     "لحم",
  //     "سمن غنمي",
  //     "بهارات خاصة",
  //     "دقس",
  //     "فلفل حار",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1-2",
  //   notes_en: "An authentic traditional taste that combines the sweetness of milk and the distinctive flavor of meat. A warm and rich meal suitable for lovers of popular dishes.",
  //   notes_ar: "طعم تقليدي أصيل يجمع بين حلاوة الحليب ونكهة اللحم المميزة. وجبة دافئة وغنية تناسب محبي الأكلات الشعبية."
  // },
  // {
  //   id: "SALEEQ-CHICKEN",
  //   code: "SALEEQ-CHICKEN",
  //   name_en: "Chicken Saleeq",
  //   name_ar: "سليق بالدجاج",
  //   desc_en: "Indulge in a plate of milk-boiled rice prepared with special flavors, served with a piece of chicken roasted in sheep ghee and spicy dakos sauce. This delicious dish is accompanied by dakos and spicy salad to give you a traditional dining experience rich in flavors.",
  //   desc_ar: "استمتع بطبق من الرز المسلوق بالحليب والمحضر بنكهة خاصة، ويقدم مع قطعة من الدجاج المحمر بالسمن الغنمي وصوص الدقس الحار. يقدم هذا الطبق الشهي مع الدقس وسلطة حارة ليمنحك تجربة طعام تقليدية غنية بالنكهات.",
  //   image: "img17",
  //   category_en: "Rices Te'ama",
  //   category_ar: "أرزاز طعمة",
  //   calories: 1190,
  //   price: 38,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "rice",
  //     "milk",
  //     "chicken",
  //     "sheep ghee",
  //     "special spices",
  //     "dakos",
  //     "chili peppers",
  //     "vegetables"
  //   ],
  //   ingredients_ar: [
  //     "أرز",
  //     "حليب",
  //     "دجاج",
  //     "سمن غنمي",
  //     "بهارات خاصة",
  //     "دقس",
  //     "فلفل حار",
  //     "خضروات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "An authentic traditional taste that combines the sweetness of milk and the distinctive flavor of chicken. A warm and rich meal suitable for lovers of popular dishes.",
  //   notes_ar: "طعم تقليدي أصيل يجمع بين حلاوة الحليب ونكهة الدجاج المميزة. وجبة دافئة وغنية تناسب محبي الأكلات الشعبية."
  // },
  {
    id: "SAMOSAMIXCHEESE",
    code: "SAMOSA-MIX-CHEESE",
    name_en: "Samosa Mix Cheese",
    name_ar: "سمبوسك طعمة",
    desc_en:
      "Enjoy a unique taste with Samosa Mix Cheese, crispy dough filled with a delicious blend of cheeses in the Madini style. A tasty light meal or a distinctive appetizer that satisfies all tastes.",
    desc_ar:
      "استمتع بمذاق فريد مع سمبوسك طعمة، رقائق مقرمشة محشوة بخليط من الأجبان اللذيذة على طريقة أهل المدينة. وجبة خفيفة شهية أو مقبل مميز يرضي جميع الأذواق.",
    image: img32,
    category_en: "pastry basket",
    category_ar: "سلة معجنات",
    calories: 342,
    price: 17,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "flour",
      "cheese mix (cheddar, mozzarella, ...)",
      "spices",
    ],
    ingredients_ar: ["دقيق", "خليط أجبان (شيدر, موزاريلا, ...)", "بهارات"],
    isVegetarian: true,
    isVegan: false,
    isGlutenFree: false,
    servings: "غير محدد",
    notes_en:
      "Irresistible crispiness and a cheese filling rich in flavor. Served hot as a snack or appetizer.",
    notes_ar:
      "قرمشة لا تقاوم وحشوة جبنة غنية بالنكهة. يقدم ساخناً كوجبة خفيفة أو مقبل.",
  },
  {
    id: "SEASPICYPOT",
    code: "SEA-SPICY-POT",
    name_en: "Sea Spicy Chips",
    name_ar: "شيبسي حارة البحر",
    desc_en:
      "Enjoy fresh potato fries served with a distinctive selection of sauces: creamy garlic sauce, rich sesame tahini, spicy green dakos, and refreshing homr salad. A perfect side dish for lovers of hot and diverse flavors.",
    desc_ar:
      "استمتع بأصابع البطاطس الطازجة المقلية والمقدمة مع تشكيلة مميزة من الصوصات: صوص الثوم الكريمي، طحينة السمسم الغنية، دقوس الأخضر الحار، وسلطة الحمر المنعشة. وجبة جانبية مثالية لعشاق النكهات الحارة والمتنوعة.",
    image: img30,
    category_en: "Breakfast/Snack",
    category_ar: "فطور/تصبيرة",
    calories: 0,
    price: 12,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "potatoes",
      "frying oil",
      "garlic",
      "tahini",
      "chili peppers",
      "tamarind",
      "spices",
    ],
    ingredients_ar: [
      "بطاطس",
      "زيت قلي",
      "ثوم",
      "طحينة",
      "فلفل حار",
      "تمر هندي",
      "بهارات",
    ],
    isVegetarian: true,
    isVegan: true,
    isGlutenFree: true,
    servings: "1-2",
    notes_en:
      "A combination of crispiness, heat, and freshness in every bite. A unique sauce experience that complements the deliciousness of the potatoes.",
    notes_ar:
      "مزيج من القرمشة والحرارة والانتعاش في كل قضمة. تجربة صوصات فريدة تكمل لذة البطاطس.",
  },
  // {
  //   id: "SFIAH-CHEESE-MOUSSAKA",
  //   code: "SFIAH-CHEESE-MOUSSAKA",
  //   name_en: "Sfiah Cheese Moussaka",
  //   name_ar: "صفيحة مسفعة بالجبن",
  //   desc_en: "Enjoy a Khadua pie with delicious mozzarella cheese. Fresh and tasty pastries, perfect as a light meal or a delicious appetizer.",
  //   desc_ar: "استمتع بصفيحة خدوة بالجبنة الموزاريلا اللذيذة. معجنات طازجة وشهية، مثالية كوجبة خفيفة أو مقبل لذيذ.",
  //   image: "img20",
  //   category_en: "Plates and sandwiches",
  //   category_ar: "صفايح وساندوتش",
  //   calories: 0,
  //   price: 12,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "flour",
  //     "mozzarella cheese",
  //     "oil",
  //     "spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "جبنة موزاريلا",
  //     "زيت",
  //     "بهارات"
  //   ],
  //   isVegetarian: true,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The rich taste of mozzarella cheese inside the soft dough. A delicious and quick choice.",
  //   notes_ar: "طعم الجبنة الموزاريلا الغنية داخل العجينة الطرية. خيار لذيذ وسريع."
  // },
  // {
  //   id: "SFIAH-SALAT-TAHINI",
  //   code: "SFIAH-SALAT-TAHINI",
  //   name_en: "Sfiah Salat with Tahini",
  //   name_ar: "صفايح سلات بالطحينة",
  //   desc_en: "Enjoy Madini Salat with Tahini, a seriously amazing combination! Fresh and tasty pastries filled with a special filling and topped with delicious tahini.",
  //   desc_ar: "استمتع بسلات المدينة والطحينة كلام خطير! معجنات طازجة وشهية محشوة بحشوة مميزة ومغطاة بالطحينة اللذيذة.",
  //   image: "img31",
  //   category_en: "Plates and sandwiches",
  //   category_ar: "صفايح وساندوتش",
  //   calories: 0,
  //   price: 12,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "flour",
  //     "minced meat or chicken",
  //     "tahini",
  //     "onion",
  //     "spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "لحم مفروم أو دجاج",
  //     "طحينة",
  //     "بصل",
  //     "بهارات"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The distinctive taste of Salat with rich tahini. A unique and delicious combination worth trying.",
  //   notes_ar: "طعم السلات المميز مع الطحينة الغنية. مزيج فريد ولذيذ يستحق التجربة."
  // },
  // {
  //   id: "SFIAH-WHITE-CHEESE-HALVA",
  //   code: "SFIAH-WHITE-CHEESE-HALVA",
  //   name_en: "Sfiah White Cheese with Halva",
  //   name_ar: "صفايح جبنة بيضاء بالحلاوة الطحينية",
  //   desc_en: "Indulge in a special mix of white cheese and halva tahini, topped with delicious pistachios. Fresh pastries that combine sweet and savory flavors in a unique and tasty way.",
  //   desc_ar: "استمتع بخليط الجبنة البيضاء والحلاوة الطحينية المميزة، والمزينة بالفستق الحلبي الشهي. معجنات طازجة تجمع بين المذاق الحلو والمالح بطريقة فريدة ولذيذة.",
  //   image: "img32",
  //   category_en: "Plates and sandwiches",
  //   category_ar: "صفايح وساندوتش",
  //   calories: 0,
  //   price: 12,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "flour",
  //     "white cheese",
  //     "halva tahini",
  //     "pistachios",
  //     "oil",
  //     "spices"
  //   ],
  //   ingredients_ar: [
  //     "دقيق",
  //     "جبنة بيضاء",
  //     "حلاوة طحينية",
  //     "فستق حلبي",
  //     "زيت",
  //     "بهارات"
  //   ],
  //   isVegetarian: true,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The creamy taste of white cheese with the rich sweetness of halva and the crunch of pistachios. A unique and delicious combination for lovers of different flavors.",
  //   notes_ar: "طعم الجبنة البيضاء الكريمية مع حلاوة الطحينية الغنية وقرمشة الفستق. مزيج فريد ولذيذ لمحبي النكهات المختلفة."
  // },
  // {
  //   id: "TRADITIONAL-MANZLAH",
  //   code: "TRADITIONAL-MANZLAH",
  //   name_en: "Traditional Manzlah",
  //   name_ar: "منزلة على الأصول",
  //   desc_en: "Indulge in tender beef chunks with rich and flavorful tahini gravy. A traditional meal rich in authentic flavors.",
  //   desc_ar: "استمتع بقطع اللحم الطرية مع مرقة الطحينة المسبكة. وجبة تقليدية وغنية بالنكهات الأصيلة.",
  //   image: "img22",
  //   category_en: "Ta'mat Al-Madinah dishes",
  //   category_ar: "أطباق  طعمة  المدينة",
  //   calories: 0,
  //   price: 45,
  //   rating: 0,
  //   available: true,
  //   trendy: false,
  //   prepTime: "غير محدد",
  //   cookTime_en: "long",
  //   difficulty_en: "medium",
  //   difficulty_ar: "متوسط",
  //   ingredients_en: [
  //     "beef chunks",
  //     "tahini",
  //     "onion",
  //     "garlic",
  //     "special spices"
  //   ],
  //   ingredients_ar: [
  //     "قطع لحم",
  //     "طحينة",
  //     "بصل",
  //     "ثوم",
  //     "بهارات خاصة"
  //   ],
  //   isVegetarian: false,
  //   isVegan: false,
  //   isGlutenFree: false,
  //   servings: "1",
  //   notes_en: "The taste of tender beef with rich and thickened tahini gravy. A warm and nutritious meal suitable for lovers of traditional dishes.",
  //   notes_ar: "طعم اللحم الطري مع مرقة الطحينة الغنية والمسبكة. وجبة دافئة ومغذية ومناسبة لمحبي الأكلات التقليدية."
  // },
  {
    id: "TAHINI-KEBAB",
    code: "TAHINI-KEBAB",
    name_en: "Tahini Kebab",
    name_ar: "كباب الطحينة",
    desc_en:
      "Indulge in special kebab grilled over charcoal and topped with rich and delicious tahini sauce. A delicious meal rich in grilled flavors and distinctive tahini.",
    desc_ar:
      "استمتع بالكباب المميز المشوي على الفحم والمغطى بصوص الطحينة الغني واللذيذ. وجبة شهية وغنية بالنكهات المشوية والطحينة المميزة.",
    image: img39,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 343,
    price: 73,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "easy",
    difficulty_ar: "سهل",
    ingredients_en: [
      "minced meat or pieces",
      "spices",
      "tahini",
      "lemon",
      "vegetables for garnish",
    ],
    ingredients_ar: [
      "لحم مفروم أو قطع",
      "بهارات",
      "طحينة",
      "ليمون",
      "خضروات للتزيين",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of grilled kebab with rich tahini sauce. A unique and delicious combination worth trying.",
    notes_ar:
      "طعم الكباب المشوي مع صوص الطحينة الغني. مزيج فريد ولذيذ يستحق التجربة.",
  },
  {
    id: "TOMAH-KEBAB",
    code: "TOMAH-KEBAB",
    name_en: "To'mah Kebab",
    name_ar: "كباب طعمة",
    desc_en:
      "Indulge in premium special kebab served with delicious nuts and rich tahini sauce. A royal meal rich in luxurious flavors and fresh ingredients.",
    desc_ar:
      "استمتع بالكباب الفاخر والمميز المقدم مع المكسرات الشهية وصوص الطحينة الغني. وجبة ملكية غنية بالنكهات الفاخرة والمكونات الطازجة.",
    image: img38,
    category_en: "Grilled Te'ama",
    category_ar: "منقل طعمة",
    calories: 343,
    price: 73,
    rating: 0,
    available: true,
    trendy: false,
    prepTime: "غير محدد",
    cookTime_en: "غير محدد",
    difficulty_en: "medium",
    difficulty_ar: "متوسط",
    ingredients_en: [
      "minced meat or pieces",
      "onion",
      "special spices",
      "nuts (almonds, pine nuts, ...)",
      "tahini",
      "lemon",
      "vegetables for garnish",
    ],
    ingredients_ar: [
      "لحم مفروم أو قطع",
      "بصل",
      "بهارات خاصة",
      "مكسرات (لوز, صنوبر, ...)",
      "طحينة",
      "ليمون",
      "خضروات للتزيين",
    ],
    isVegetarian: false,
    isVegan: false,
    isGlutenFree: false,
    servings: "1",
    notes_en:
      "The taste of premium kebab with the rich crunch of nuts and distinctive tahini sauce. An exceptional dining experience and an unforgettable taste.",
    notes_ar:
      "طعم الكباب الفاخر مع قرمشة المكسرات الغنية وصوص الطحينة المميز. تجربة طعام استثنائية ومذاق لا يُنسى.",
  },
  // {
  //   id: "SAQDANA-AM-KHALIL",
  //   code: "SAQDANA-AM-KHALIL",
  //   name_en: "Am Khalil's Saqdana",
  //   name_ar: "سقدانة عم خليل",
  //   desc_en: "Hijazi dessert made of sago pearls and milk.",
  //   desc_ar: "طبق حجازي شهير يحضر بالساجو والحليب.",
  //   image: "img-saqdana",
  //   category_en: "Desserts",
  //   category_ar: "حلويات",
  //   calories: 481,
  //   price: 20,
  //   rating: 0,
  //   available: true,
  //   trendy: true,
  //   prepTime: "غير محدد",
  //   cookTime_en: "غير محدد",
  //   difficulty_en: "easy",
  //   difficulty_ar: "سهل",
  //   ingredients_en: [
  //     "sago pearls",
  //     "milk",
  //     "sugar",
  //     "rose water",
  //     "cardamom",
  //     "pistachios (for garnish)"
  //   ],
  //   ingredients_ar: [
  //     "ساجو",
  //     "حليب",
  //     "سكر",
  //     "ماء ورد",
  //     "هيل",
  //     "فستق (للتزيين)"
  //   ],
  //   isVegetarian: true,
  //   isVegan: false,
  //   isGlutenFree: true,
  //   servings: "1",
  //   notes_en: "A famous Hijazi dessert, sweet and refreshing, perfect after a meal.",
  //   notes_ar: "حلوى حجازية شهيرة، حلوة ومنعشة، مثالية بعد الوجبات."
  // }
  //the end of pages from 13 to 18 40s
];

export default productsData;
